--[[
    SAMBUNG KATA AUTO - V17.4 FINAL
    - Deteksi prefix lebih akurat (hanya 1-3 huruf).
    - Scan otomatis hanya mengambil UI dengan prefix valid.
    - Blacklist diperluas.
    - Logging detail.
]]

local Rayfield = loadstring(game:HttpGet('https://sirius.menu/rayfield'))()
local VIM = game:GetService("VirtualInputManager")
local VU = game:GetService("VirtualUser")
local LP = game.Players.LocalPlayer

-- ==================== SAMPLE DATABASE (10 KATA) ====================
local kataKBBI = {
    "ABSIS", "ADNEKS", "ADOPS", "AFIKS", "AJEKS", "AKSEPTIF", "AKUNTATIF", "ALFABET", "ALOMORF", "ALOTROF", "AMFIBI", "AMFIKS", "AMORF", "AMP", "AMUBA", "ANABASIS", "ANAKRONISTIS", "ANALOG", "ANARKIS", "ANASIR", "ANDIL", "ANDRAGOGI", "ANDROGINI", "ANEKS", "ANSAMBEL", "ANTARKLUB", "ANTITESIS", "ANTRAKS", "ANTROPOMORF", "APATIS", "APEKS", "APENDIKS", "APOGRAF", "APOKRIF", "APOLITIS", "APORETIS", "ASERTIF", "ASFIKS", "ASKETIS", "ASINKRON", "ASISTENS", "ASOSIATI", "ASONANSI", "ASTIGMATIS", "ASIMTOTI", "ASIMTUT", "ATAKTIS", "ATEIS", "ATENUASI", "ATOMIS", "AUTOKARP", "AUTOKTON", "AUTOLISIS", "AUTONOM", "AUTORADIOGRAF", "AUTOTIPE", "AVONTUR", "AWAT", "AWET", "AZIMAT", "AZIS", "BISEPS", "CAMP", "DEKS", "DEKTOS", "DOLF", "DOPS", "DRAF", "DREL", "DROP", "DRUMBEN", "DUET", "DUPS", "EDISI", "EFEK", "EFENDI", "EKA", "EKH", "EKS", "EKSAK", "EKSIS", "EKSIT", "EKSONS", "EKSPOS", "EKSTREM", "EKTE", "ELIPS", "EMPAT", "EMULSI", "ENANS", "ENGKAP", "ENGLAP", "ENGSAP", "ENTIT", "EPS", "ESAIS", "ESENS", "ESTETIS", "ETIS", "ETOS", "EUFEMIS", "EUFONIATIS", "EUFOTIS", "EVAKUATIF", "EVOLUTIF", "FAKTUAL", "FAKULTATIF", "FASIK", "FISIS", "FLEKS", "FLUKS", "FOKAL", "FOKS", "FOKUS", "FONS", "FORSEP", "FUNGSIONAL", "GIPS", "GOLF", "HAMS", "HARKAT", "HIPOTESIS", "HORISONTALIS", "HOV", "HUMUS", "IATRIS", "IDENTIK", "IDIOPATIS", "IMPULS", "INDEKS", "INDUS", "INERS", "INFIKS", "INFORMATIF", "INISIATIF", "INISIF", "INKLUSIF", "INSTING", "INSTINGTIF", "INSTRUKTIF", "INTENS", "INTERUPSI", "INTRINSIK", "INTROSPEKSI", "INTUITIF", "ISOBARIK", "ISOMORF", "ISOMORFIS", "ISOTOP", "JAZ", "JENGAT", "JENGIT", "JIPS", "JIPSI", "JUKSTAPOS", "KAFI", "KAGET", "KAIS", "KALS", "KAMP", "KAMPF", "KANTI", "KANTIF", "KAP", "KARAF", "KARAK", "KARAP", "KARAS", "KARS", "KARSIS", "KART", "KARTU", "KAS", "KASIF", "KASET", "KATARSIS", "KATEGORIAL", "KATES", "KATUT", "KELAP", "KELES", "KELIP", "KELIT", "KELOT", "KELUT", "KEMP", "KEMPOT", "KEMPU", "KEMPUL", "KENS", "KEP", "KEPING", "KEPIT", "KEPUL", "KEPUNG", "KERAH", "KERAK", "KERAKAL", "KERAMAS", "KERAMAT", "KERAMBA", "KERAMBIT", "KERAMIK", "KERAN", "KERANDA", "KERANG", "KERANJANG", "KERAP", "KERAS", "KERATAN", "KERATON", "KERBAU", "KERDIL", "KERDIPAN", "KEREK", "KEREN", "KERETA", "KERIK", "KERIKIL", "KERINDUAN", "KERING", "KERIS", "KERITIK", "KERJA", "KERLING", "KERNA", "KERONCONG", "KERTAS", "KERUBUNG", "KERUMUN", "KERUPUK", "KERUT", "KESAH", "KESAN", "KESAT", "KESELEO", "KESET", "KESIA", "KESIT", "KESITU", "KESOHOR", "KETAM", "KETAN", "KETAT", "KETAWA", "KETIAK", "KETIBAN", "KETIKA", "KETIWAK", "KETOPRAK", "KETUJUH", "KETUK", "KETUMBAR", "KETUPAT", "KHAWATIR", "KHAT", "KHATULISTIWA", "KHAYAL", "KHAZANAH", "KHIANAT", "KHIDMMAT", "KHITAN", "KHOTBAH", "KHUSUS", "KIAMAT", "KIAN", "KIANI", "KIAS", "KIBAR", "KIBAS", "KIBLAT", "KIDAL", "KIDUNG", "KIKIR", "KIKIS", "KILAN", "KILAS", "KILAT", "KILAU", "KILI", "KILIR", "KILO", "KIMAH", "KIMIA", "KIMLO", "KIMO", "KIMPUL", "KINA", "KINCIR", "KINER", "KINERJA", "KINI", "KINYIS", "KIPAS", "KIRA", "KIRAB", "KIRAI", "KIRANYA", "KIRIM", "KIRING", "KIRMIZI", "KIRS", "KISA", "KISAH", "KISAR", "KISI", "KISRUH", "KISTA", "KISUT", "KITA", "KITAB", "KITAR", "KLAN", "KLASIFIKASI", "KLASIK", "KLAUSUL", "KLIK", "KLIEN", "KLIMAKS", "KLINIK", "KLIPING", "KLISE", "KLONING", "KLORIN", "KLUB", "KNALPOT", "KOALA", "KOALISI", "KOBOI", "KOCAK", "KOCOK", "KODE", "KODRAT", "KOEFISIEN", "KOHESI", "KOIN", "KOKOH", "KOKI", "KOLAM", "KOLERA", "KOLEKSI", "KOLEKTIF", "KOLESTEROL", "KOLONG", "KOLOM", "KOLONI", "KOLOSAL", "KOMA", "KOMANDAN", "KOMEDI", "KOMENTAR", "KOMERSIAL", "KOMIDI", "KOMIK", "KOMISI", "KOMITMEN", "KOMODITAS", "KOMON", "KOMPAK", "KOMPAS", "KOMPENI", "KOMPENSASI", "KOMPETISI", "KOMPI", "KOMPLAIN", "KOMPLOTAN", "KOMPONEN", "KOMPOSISI", "KOMPRES", "KOMPROMI", "KOMPUTER", "KOMUNIS", "KONDISI", "KONDUKTOR", "KONEKSI", "KONFERENSI", "KONFLIK", "KONGKONG", "KONGRES", "KONJUNGSI", "KONKRIT", "KONON", "KONPERENSI", "KONSEP", "KONSER", "KONSERVASI", "KONSISTEN", "KONSOL", "KONSPIRASI", "KONSTAN", "KONSTRUKSI", "KONSULTASI", "KONSUMSI", "KONTAK", "KONTAMINASI", "KONTEKS", "KONTEMPORER", "KONTES", "KONTINGEN", "KONTINU", "KONTRAK", "KONTRAKSI", "KONTRAS", "KONTRIBUSI", "KONTROL", "KONVEKSI", "KONVENSI", "KONVOI", "KOPER", "KOPERASI", "KOPI", "KOPIAH", "KOPLAK", "KOPLING", "KOPRAL", "KOPROK", "KORAL", "KORAN", "KORBAN", "KORDEN", "KOREK", "KOREKSI", "KORENG", "KORES", "KORESPONDEN", "KORIDOR", "KORNEA", "KORNET", "KOROSI", "KORPS", "KORSLETING", "KORUPSI", "KOSA", "KOSAKAT", "KOSAMBI", "KOSAN", "KOSEK", "KOSMETIK", "KOSMIK", "KOSMONOT", "KOSONG", "KOSTUM", "KOTA", "KOTAK", "KOTBAH", "KOTOR", "KOWAD", "KOWALK", "KOYAK", "KRAN", "KRAYON", "KREASI", "KREATIF", "KREDIT", "KREM", "KREMASI", "KRESEK", "KRIBO", "KRIMINIL", "KRIS", "KRISIS", "KRISTAL", "KRITERIA", "KRITIK", "KROMO", "KRONIS", "KSATRIA", "KUACI", "KUADRAN", "KUADRAT", "KUAH", "KUALA", "KUALI", "KUALITAS", "KUANTITAS", "KUAS", "KUASA", "KUAT", "KUATIR", "KUBAH", "KUBANG", "KUBIK", "KUBIS", "KUBU", "KUBUR", "KUCAI", "KUCEL", "KUCING", "KUCIR", "KUCUR", "KUDA", "KUDAPAN", "KUDI", "KUDIS", "KUDRAT", "KUDUS", "KUE", "KUETIAU", "KUFU", "KUIL", "KUINTAL", "KUINTET", "KUIS", "KUITANSI", "KUKU", "KUKUH", "KUKUS", "KULAI", "KULAT", "KULI", "KULIAH", "KULINER", "KULIT", "KULKAS", "KULMINASI", "KULO", "KULON", "KULOT", "KULTURAL", "KULTUR", "KUMAN", "KUMANDANG", "KUMBANG", "KUMIS", "KUMPUL", "KUMUH", "KUMUR", "KUNANG", "KUNCEN", "KUNCI", "KUNCUP", "KUNDA", "KUNING", "KUNJUNG", "KUNNO", "KUNTUM", "KUNYAH", "KUNYIT", "KUOTA", "KUPER", "KUPAS", "KUPAT", "KUPING", "KUPON", "KUPU", "KURA", "KURANG", "KURAS", "KURATOR", "KURAWAL", "KURBAN", "KURCACI", "KURIA", "KURIKULUM", "KURIR", "KURMA", "KURNIA", "KURS", "KURSI", "KURSUS", "KURUN", "KURUNG", "KURUS", "KUSA", "KUSAM", "KUSTA", "KUSU", "KUSUT", "KUTANG", "KUTU", "KUTUB", "KUTUKAN", "KUTUT", "KUWERA", "KWARCIT", "KWARTAL", "KWARTIR", "LABA", "LABAH", "LABANG", "LABAS", "LABEL", "LABERANG", "LABI", "LABIL", "LABIRIN", "LABRAK", "LABU", "LABUH", "LACAK", "LACI", "LACUR", "LADA", "LADANG", "LADEN", "LADING", "LADUNG", "LAFAL", "LAGA", "LAGAM", "LAGI", "LAGU", "LAHAD", "LAHAP", "LAAR", "LAHIR", "LAIK", "LAIS", "LAJU", "LAJUR", "LAKI", "LAKNAT", "LAKON", "LAKSA", "LAKSANA", "LAKU", "LALA", "LALAI", "LALAK", "LALAT", "LALAU", "LALER", "LALI", "LALU", "LAMA", "LAMBANG", "LAMBAT", "LAMBE", "LAMBUNG", "LAMUN", "LAMUR", "LANA", "LANANG", "LANAU", "LANCAR", "LANCUNG", "LANCUR", "LANDA", "LANDAI", "LANDAK", "LANDAS", "LANGGANAN", "LANGGAR", "LANGGENG", "LANGI", "LANGIT", "LANGKA", "LANGKAH", "LANGKAN", "LANGKAS", "LANGKAT", "LANGKING", "LANGKUNG", "LANGLANG", "LANGSA", "LANGSAR", "LANGSAT", "LANGSI", "LANGSUNG", "LANJUT", "LANJUR", "LANSIA", "LANSI", "LANTAI", "LANTAS", "LENTERA", "LENTUR", "LANYAU", "LAOS", "LAPANG", "LAPAR", "LAPAT", "LAPEL", "LAPIS", "LAPOR", "LAPUK", "LARA", "LARAI", "LARAK", "LARANG", "LARAS", "LARAT", "LARI", "LARIK", "LARIS", "LARON", "LARUT", "LASUH", "LATA", "LATAH", "LATAK", "LATAR", "LATIH", "LATIN", "LATUNG", "LATUR", "LAUK", "LAUN", "LAUNG", "LAUT", "LAWA", "LAWAK", "LAWAN", "LAWANG", "LAWAR", "LAWAS", "LAWAT", "LAYAK", "LAYAM", "LAYAN", "LAYANG", "LAYAP", "LAYAR", "LAYAS", "LAYAT", "LAYU", "LAYUR", "LAZAT", "LAZIM", "LEBAH", "LEBAI", "LEBAK", "LEBAM", "LEBAR", "LEBAS", "LEBAT", "LEBER", "LEBIH", "LEBUH", "LEBUNG", "LEBUR", "LECA", "LECEH", "LECEK", "LECET", "LECIT", "LECUR", "LECUT", "LEDAK", "LEDANG", "LEDEK", "LEDENG", "LEDER", "LEDOS", "LEDUK", "LEGA", "LEGAK", "LEGAL", "LEGAM", "LEGAP", "LEGAR", "LEGAS", "LEGAT", "LEGENDA", "LEGER", "LEGIT", "LEGO", "LEGONG", "LEGU", "LEGUM", "LEGUNG", "LEHAR", "LEHER", "LEKA", "LEKAH", "LEKAM", "LEKAN", "LEKAP", "LEKAR", "LEKAS", "LEKAT", "LEKEH", "LELAP", "LELAR", "LELAS", "LELAT", "LELEH", "LELEP", "LELER", "LELES", "LELUASA", "LELUCON", "LELUHUR", "LULUR", "LULUS", "LUMAT", "LUMBA", "LUMBUNG", "LUMPUH", "LUMPUR", "LUMRAH", "LUMU", "LUMUR", "LUMUT", "LUNAK", "LUNAS", "LUNCAS", "LUNCUR", "LUNDUN", "LUNGLAI", "LUNGSIN", "LUNJUR", "LUNTUR", "LUPA", "LUPUT", "LURAH", "LURIK", "LURUH", "LURUS", "LUSA", "LUSIN", "LUSU", "LUTUT", "LUWES", "MAAFI", "MAAF", "MABUK", "MACAN", "MACAT", "MACE", "MACET", "MADAH", "MADANI", "MADAT", "MADRASAH", "MADU", "MAFHUM", "MAUT", "MAWAR", "MAYA", "MAYAM", "MAYANG", "MAYAT", "MAYOR", "MAYSA", "MAZA", "MAZHAB", "MEBEL", "MEDAN", "MEDIA", "MEDIATOR", "MEDIS", "MEDITASI", "MEGA", "MEGAH", "MEGANG", "MEGAR", "MEJA", "MEKAR", "MEKANISME", "MELANKOLIS", "MELATI", "MELAYU", "MELEK", "MELESIT", "MELODI", "MELONGO", "MELULU", "MEMANG", "MEMAR", "MEMENTO", "MEMO", "MENANG", "MENANGIS", "MENANTU", "MENCAK", "MENDING", "MENENG", "MENGERTI", "MENTAH", "MENTARI", "MENTEGA", "MENTERI", "MENTOK", "MENTOL", "MENU", "MANUSIA", "MENYAPA", "MERAH", "MERANA", "MERANTI", "MERDEKA", "MERDU", "MEREKA", "MERIAH", "MIRING", "MIRIP", "MIRIS", "MIRTUL", "MISA", "MISAL", "MISKIN", "MISTAR", "MISTERI", "MISTIS", "MITRA", "MIYANG", "MOBIL", "MODIS", "MOGA", "MOGOK", "MOHON", "MOLEK", "MOMEN", "MOMENTUM", "MONITOR", "MONOLOG", "MONOPOLI", "MOSI", "MOTIVASI", "MUAL", "MUARA", "MUAT", "MUAZIN", "MUDA", "MUDAH", "MUDIK", "MUFA", "MUFAKAT", "MUFTI", "MUHIBAH", "MUHRIM", "MUIS", "MUJA", "MUJARAB", "MUJUR", "MUKA", "MUKIM", "MUKJIZAT", "MUKMIN", "MULA", "MULAI", "MULIA", "MULSA", "MULUT", "MUMBUL", "MUMPUNI", "MUNCUL", "MUNDING", "MUNDUR", "MUNGIL", "MUNGKIN", "MUNGKUR", "MUNGKUT", "MUNGSI", "MUNISI", "MUNJUL", "MUNAJAT", "MUNJUNJUNG", "MUNSYI", "MUNTAH", "MUNTIL", "MUNU", "MUPAKAT", "MURAH", "MURAM", "MURBA", "MURBAI", "MURID", "MURING", "MURNI", "MURKA", "MURTAD", "MURUNG", "MUSA", "MUSABAB", "MUSAFIR", "MUSANG", "MUSYAWARAH", "MOSEUM", "MUSIK", "MUSIM", "MUSLIHAT", "MUSNA", "MUSNAH", "MUSTAHIL", "MUSUH", "MUTASI", "MUTIARA", "MUTLAK", "MUTU", "NABI", "NADA", "NADI", "NAFAS", "NAFKAH", "NAFSI", "NAFSU", "NAGA", "NAHAS", "NAHU", "NAIK", "NAJIS", "NAKAL", "NAKHODA", "NALAR", "NAMA", "NAMPAK", "NAMPAN", "NAMUN", "NANAH", "NANAP", "NANAR", "NENAS", "NANGKA", "NANTI", "NAPAS", "NAPU", "NARA", "NARASI", "NARATIF", "NARKOBA", "NASAB", "NASEHAT", "NASI", "NASIB", "NASIHAT", "NASIONAL", "NASKAH", "NASRANI", "NATAL", "NATRIUM", "NAUNG", "NURANI", "NUSA", "NUSANTARA", "NUTRISI", "NUANSA", "NYALA", "NYAMAN", "NYAMUK", "NYANYI", "NYARING", "NYATA", "NYAWA", "NYENYAK", "NYONYA", "OBAL", "OBAR", "OBAT", "OBENG", "OBJEK", "OBJEKTIF", "OBLIGASI", "OBLONG", "OBOR", "OBRAK", "OBRAL", "OBROL", "OBSESI", "OBSERVASI", "OBSIDIAN", "OKNUM", "OKTAF", "OKULER", "OLES", "OLAHRAGA", "OLEH", "OLOK", "OMBAK", "OMEL", "OMONG", "OMPONG", "ONAK", "ONAR", "ONDERDIL", "ONGKOS", "ONTA", "OPERASI", "OPNAME", "OPTIMIS", "OPSI", "OPTIK", "ORANG", "ORASI", "ORBIT", "ORDER", "ORGANISASI", "ORISINAL", "ORNAMEN", "OSPEK", "OTAK", "OTENTIK", "OTOBIOGRAFI", "OTOT", "OVAL", "OVEN", "OYAK", "OZON", "PABEAN", "PABEL", "PABRIK", "PACAR", "PACU", "PADAM", "PADAN", "PADANG", "PADAS", "PADAT", "PADERI", "PADU", "PADUAN", "PAGAR", "PAGI", "PAGU", "PAGUT", "PAHA", "PAHALA", "PAHAM", "PAHAS", "PAHAT", "PAHIT", "PAHLAWAN", "PAILIT", "PAJAK", "PAJANG", "PAJAR", "PAJUH", "PAKAI", "PAKAL", "PAKAN", "PAKAR", "PAKAT", "PAKIS", "PAKSA", "PAKTA", "PAKU", "PALADIN", "PALAI", "PALANG", "PALAPA", "PALAS", "PALAT", "PALAU", "PALEM", "PALEN", "PALES", "PALET", "PALING", "PALIS", "PALIT", "PALU", "PALUN", "PALUNG", "PAMAN", "PAMAH", "PAMER", "PAMIT", "PAMONG", "PAMOR", "PAMPAS", "PAMPAT", "PAMPA", "PAMUR", "PANAH", "PANAS", "PANAU", "PANCA", "PANCAR", "PANCING", "PANCIT", "PANCUR", "PANCUT", "PANDAI", "PANDAK", "PANDAN", "PANDANG", "PANDU", "PANEL", "PANGAH", "PANGAN", "PANGERAN", "PANGESTU", "PANGGUL", "PANGGUNG", "PANGGIL", "PANGKAI", "PANGKAS", "PANGKAT", "PANGKAL", "PANGKON", "PANGKU", "PANGLIMA", "PANGLONG", "PANGONAN", "PANGSA", "PANGSI", "PANGUR", "PANITIA", "PANITERA", "PANJANG", "PANJAR", "PANJAT", "PANJI", "PANJUL", "PANTAI", "PANTANG", "PANTAS", "PANTAT", "PANTAU", "PANTEK", "PANTI", "PANTIK", "PANTIS", "PANTUL", "PANTUN", "PANU", "PANUS", "PAPA", "PAPAH", "PAPAK", "PAPAN", "PAPAR", "PAPAS", "PAPAT", "PARAH", "PARAFE", "PARAFIN", "PARAGRAF", "PARAK", "PARAM", "PARANG", "PARAP", "PARAS", "PARAT", "PARAU", "PARIT", "PARKIR", "PARLEMEN", "PARODI", "PAROKI", "PARON", "PARUH", "PARUT", "PASAH", "PASAK", "PASAL", "PASANG", "PASAR", "PASAS", "PASAT", "PASER", "PASET", "PASFOTO", "PASIF", "PASIR", "PASIT", "PASMA", "PASRAH", "PASTA", "PASTI", "PASU", "PASUH", "PASUNG", "PATAH", "PATAM", "PATAR", "PATEK", "PATEN", "PATERA", "PATIH", "PATIK", "PATIL", "PATIN", "PATIR", "PATIT", "PATOK", "PATROLI", "PATRON", "PATUH", "PATUK", "PATUL", "PATUNG", "PATUT", "PAUH", "PAUK", "PAUS", "PAUT", "PAVILIUN", "PAWAI", "PAWANG", "PAYA", "PAYAH", "PAYANG", "PAYAR", "PAYAT", "PAYAU", "PAYIR", "PAYU", "PAYUNG", "PEBERI", "PECAH", "PECAI", "PECAK", "PECAL", "PECARA", "PECAT", "PECEL", "PECINAN", "PECUT", "PEDAGANG", "PEDAH", "PEDAKA", "PEDAL", "PEDALAMAN", "PEDANDA", "PEDANG", "PEDAR", "PEDAS", "PEDATI", "PEDEL", "PEDEWAK", "PEDIH", "PEDIS", "PEDOK", "PEDU", "PEDULI", "PEGAGAN", "PEGAL", "PEGAN", "PEGANG", "PEGANGAN", "PEGAR", "PEGAS", "PEGAWAI", "PEGUN", "PEHONG", "PEKA", "PEKAK", "PEKAN", "PEKAP", "PEKAS", "PEKAT", "PEKER", "PEKI", "PEKING", "PEKIR", "PEKIS", "PEKUR", "PELABI", "PELAH", "PELAMIN", "PELAMPUNG", "PELANA", "PELANCONG", "PELANGI", "PELANTING", "PELAPIS", "PELAPOR", "PELAT", "PELATUK", "PELAUT", "PELAYON", "PELBAGAI", "PELEBAYA", "PELEPAH", "PELESIR", "PELESIT", "PELET", "PELETIK", "PELETING", "PELIAS", "PELIHARA", "PELIK", "PELING", "PELINTIR", "PELIPIS", "PELIPIT", "PELIPUR", "PELIR", "PELIT", "PELITA", "PELITUR", "PELONCO", "PELOSOK", "PELOPOR", "PELOR", "PELOS", "PELUH", "PELUIT", "PELUK", "PELUNTUR", "PELURU", "PEMAJANG", "PEMALAK", "PEMALI", "PEMANTUL", "PEMAR", "PEMAT", "PEMBANTU", "PEMBEDAH", "PEMEO", "PEMER", "PEMICU", "PEMIDANA", "PEMIDANG", "PEMIKAT", "PEMILU", "PEMIRSA", "PEMUDA", "PEMUDI", "PENAT", "PENCAK", "PENCAR", "PENCET", "PENCIL", "PENCUT", "PENDA", "PENDAM", "PENDEK", "PENDAPA", "PENDE", "PENDING", "PENDOPO", "PENEMBAK", "PENGANTEN", "PENGARUH", "PENGGAL", "PENGHULU", "PENING", "PENITI", "PENJARA", "PENJURU", "PENSIL", "PENSIUN", "PENTAL", "PENTAS", "PENTIL", "PENTING", "PENTOL", "PENTUNG", "PENUH", "PEPAH", "PEPAK", "PEPAS", "PEPATAH", "PEPAYA", "PEPEDAN", "PEPEK", "PEPES", "PEPET", "PERAH", "PERAHU", "PERAI", "PERAJURIT", "PERAK", "PERAN", "PERANCAH", "PERANCIS", "PERANG", "PERANTI", "PERAS", "PERAT", "PERAWAN", "PERBA", "PERCAYA", "PERCIK", "PERCUL", "PERCUMA", "PERDANA", "PERDATA", "PERDU", "PEREDAM", "PEREMBU", "PEREMPUAN", "PERES", "PERETEL", "PERGALA", "PERGAM", "PERGI", "PERGOK", "PERHAL", "PERHATI", "PERIA", "PERIBAHASA", "PERIBADI", "PERIGI", "PERIKSA", "PERINCI", "PERINDU", "PERINGAT", "PERINTAH", "PERIODE", "PERISAI", "PERISTIWA", "PERIUK", "PERKAKAS", "PERKARA", "PERKASA", "PERKEDEL", "PERKEMAHAN", "PERKUTUT", "PERLAHAN", "PERLAMBANG", "PERLENTE", "PERLUS", "PERMAI", "PERMAISURI", "PERMANEN", "PERMATA", "PERMADI", "PERMEN", "PERMISI", "PERMUKIMAN", "PERNAH", "PEROI", "PERON", "PELOS", "PEROSOK", "PEROT", "PERSADA", "PERSAHABATAN", "PERSEN", "PERSEP", "PERSEPULUH", "PERSEPSI", "PERSERO", "PERSETUJUAN", "PERSIS", "PERSON", "PERTAMA", "PERTIWI", "PERUM", "PERWARA", "PERWIRA", "PESAK", "PESAKA", "PESANGGRAHAN", "PESAT", "PESAWAT", "PESIAR", "PESIMIS", "PESINIS", "PESISIR", "PESONA", "PESTA", "PESUT", "PETAH", "PETAI", "PETAK", "PETAKA", "PETAL", "PETAM", "PETANG", "PETAR", "PETAS", "PETATAS", "PETEK", "PETENTENG", "PETER", "PETERA", "PETIK", "PETILAN", "PETIR", "PETIS", "PETISI", "PETOLA", "PETUAH", "PETUNJUK", "PIAGAM", "PIALA", "PIAMA", "PIANG", "PIANO", "PIARA", "PIATU", "PICAH", "PICIK", "PICIS", "PICIT", "PICU", "PIDANA", "PIDATO", "PIHAK", "PIJAK", "PIJAR", "PIJAT", "PIKAT", "PIKIR", "PIKUL", "PIKUN", "PILAR", "PILAT", "PILEK", "PILIH", "PILIN", "PILIS", "PILON", "PILOT", "PIMPIN", "PINAK", "PINANG", "PINAR", "PINCANG", "PINCUK", "PINDAH", "PINDAI", "PINDANG", "PINDING", "PINDU", "PINIS", "PINISI", "PINJAM", "PINSET", "PINTA", "PINTAL", "PINTAR", "PINTAS", "PINTIL", "PINTU", "PION", "PIPET", "PIPIS", "PIPIT", "PIRAI", "PIRAMIDA", "PIRANG", "PIRANTI", "PIRASAT", "PIRING", "PIRSA", "PIRUS", "PISAH", "PISANG", "PISAU", "PISIK", "PISPOT", "PISTA", "PISTOL", "PITAR", "PITING", "PIUTANG", "PLEIDOI", "PLENO", "PLESTER", "PLONCO", "POCOK", "POCONG", "PODIUM", "POHON", "POJOK", "POKOK", "POLAN", "POLANG", "POLAS", "POLDA", "POLEMIK", "POLEN", "POLER", "POLES", "POLET", "POLIKLINIK", "POLIMER", "POLIS", "POLISI", "POLITIK", "POLON", "POLONG", "POLOS", "POLUSI", "POLUTAN", "POMPA", "PONDOK", "PONDONG", "PONGAH", "PONIS", "PONOK", "PONSEL", "PONTANG", "PONTON", "PONYA", "POPI", "POPULER", "POPOK", "POPOR", "PORAK", "PORANDA", "PORNO", "POROS", "PORSI", "PORTAL", "PORTER", "PORSELEN", "POSISI", "POSITIF", "POSKO", "POSMEN", "POSTER", "POSTUR", "POTAS", "POTENSI", "POTONG", "POTRET", "POYANG", "PRABAKTI", "PRABOT", "PRABU", "PRADA", "PRADANA", "PRADESA", "PRADUGA", "PRAHARA", "PRAHOTO", "PRAJURIT", "PRAKARSA", "PRAKARYA", "PRAKATA", "PRAKIRAAN", "PRAKTEK", "PRAKTIS", "PRAMUSAJI", "PRAMUWISATA", "PRANGKO", "PRASARANA", "PRASASTI", "PRASEJARAH", "PRASMANAN", "PRASANGKA", "PRASETYA", "PRASTAWA", "PRAWIRA", "PRIBADI", "PRIBUMI", "PRIHATIN", "PRIMADONA", "PRIMER", "PRINSIP", "PRIORITAS", "PRISMA", "PRIVASI", "PRIVAT", "PRODUK", "PROFESOR", "PROFIL", "PROGRAM", "PROGRESIF", "PROKLAMASI", "PROMOSI", "PROPORSI", "PROPOSAL", "PROSEDUR", "PROSES", "PROFESI", "PROTEKSI", "PROTOKOL", "PROYEK", "PROYEKSI", "PUASA", "PUBLIK", "PUCAT", "PUCUK", "PUDAK", "PUDAR", "PUDING", "PUGAR", "PUGAS", "PUGUH", "PUJA", "PUJI", "PUJUT", "PUKAT", "PUKAU", "PUKUL", "PULANG", "PULAN", "PULAS", "PULAU", "PULES", "PULIH", "PULPEN", "PULSA", "PULUH", "PULUNG", "PULUT", "PUNAH", "PUNAKAWAN", "PUNAT", "PUNCA", "PUNCAK", "PUNDAK", "PUNDI", "PUNDIT", "PUNDUNG", "PUNGGAH", "PUNGGAWA", "PUNGGUNG", "PUNGKAS", "PUNGKUR", "PUNGLI", "PUNGUT", "PUNIA", "PUNYA", "PUPUK", "PUPUR", "PUPUS", "PUPUT", "PURBA", "PURBAKALA", "PURIT", "PURNAMA", "PURUT", "PUSAT", "PUSER", "PUSING", "PUSPA", "PUSAKA", "PUSARA", "PUSTAKA", "PUSTA", "PUTIS", "PUTRA", "PUTRI", "PUTUS", "PUYENG", "PUYUH", "QARI", "QARIAH", "QASAR", "QASIDAH", "QIAMULAIL", "QIRAAH", "QURAN", "RABAA", "RABAK", "RABAN", "RABAT", "RABIT", "RABUK", "RABUN", "RABUNG", "RACAK", "RACAU", "RACIK", "RACUN", "RADAK", "RADAM", "RADAN", "RADAR", "RADEN", "RADIKAL", "RADIO", "RADIUS", "RAFAKSI", "RAGAM", "RAGAS", "RAGHU", "RAGUM", "RAGUNG", "RAGUT", "RAHANG", "RAHAP", "RAHASIA", "RAHAT", "RAHAYU", "RAHIB", "RAHIM", "RAHMAN", "RAHMAT", "RAHSIA", "RAJAH", "RAJAM", "RAJAN", "RAJAWALI", "RAJIN", "RAJOK", "RAJUT", "RAKAAT", "RAKAM", "RAKAN", "RAKAP", "RAKAT", "RAKET", "RAKIT", "RAKSA", "RAKSASA", "RAKUN", "RAKUS", "RAKYAT", "RALAT", "RAMAH", "RAMAI", "RAMAL", "RAMAS", "RAMBAH", "RAMBAI", "RAMBAK", "RAMBAN", "RAMBAT", "RAMBU", "RAMBUT", "RAMIN", "RAMPAI", "RAMPAK", "RAMPAS", "RAMPAT", "RAMPING", "RAMPOK", "RAMPUNG", "RAMUS", "RANAH", "RANAI", "RANAP", "RANCA", "RANCAK", "RANCANG", "RANCAP", "RANCAU", "RANCU", "RANDA", "RANDAI", "RANDAT", "RANDAU", "RANDEK", "RANDU", "RANDUNG", "RANGAK", "RANGGA", "RANGGAH", "RANGGAK", "RANGGAM", "RANGGAS", "RANGGI", "RANGGUNG", "RANGKA", "RANGKAI", "RANGKAK", "RANGKAM", "RANGKANG", "RANGKAP", "RANGKAS", "RANGKET", "RANGKUH", "RANGKUL", "RANGKUM", "RANGKUNG", "RANGKUP", "RANGRANG", "RANGSANG", "RANGUM", "RANJANG", "RANJAU", "RANJI", "RANJU", "RANSEL", "RANSUM", "RANTAI", "RANTAM", "RANTAU", "RANTE", "RANTI", "RANTING", "RANTU", "RANTUS", "RANYAH", "RANYAH", "RANYAU", "RANYUN", "RANYUT", "RAPAT", "RAPIH", "RAPIK", "RAPOR", "RAPUH", "RAPUN", "RAPUS", "RARAI", "RARAK", "RARAS", "RASAI", "RASAM", "RASAMALA", "RASAN", "RASANYA", "RASIAN", "RASIONAL", "RASISME", "RASUL", "RASULULLAH", "RASUT", "RATAH", "RATAP", "RATAS", "RATIH", "RATNA", "RATUS", "RAUH", "RAUM", "RAUNG", "RAUP", "RAUT", "RAWAH", "RAWAN", "RAWAT", "RAWIT", "RAWON", "RAYAH", "RAYAN", "RAYANG", "RAYAP", "RAZIA", "REAKTIF", "REALIS", "REALITA", "REBAH", "REBAK", "REBAN", "REBANA", "REBAS", "REBAT", "REBEH", "REBEHAL", "REBEK", "REBET", "REBOK", "REBON", "REBUS", "REBUT", "RECAH", "RECAK", "RECAP", "RECEH", "RECIK", "RECOK", "REDAH", "REDAM", "REDAP", "REDAS", "REDIH", "REDIK", "REDOKS", "REDUKSI", "REDUP", "REDUSIR", "REFERENSI", "REFLEKS", "REFORMASI", "REGAN", "REGANG", "REGAS", "REGAT", "REGEL", "REGUK", "REGUNG", "REGUP", "REHABILITASI", "REHAT", "REJAH", "REJAM", "REJAN", "REJASA", "REJEKI", "REJENG", "REJUK", "REKAH", "REKAM", "REKAN", "REKAP", "REKAT", "REKAYASA", "REKLAME", "REKOR", "REKREASI", "REKRUT", "RELAI", "RELAKS", "RELASI", "RELATIF", "RELUNG", "REMAH", "REMAI", "REMAJA", "REMAK", "REMANG", "REMAS", "REMAT", "REMBAH", "REMBAK", "REMBANG", "REMBAT", "REMBET", "REMBIH", "REMBUK", "REMBULAN", "REMBUT", "REMEH", "REMET", "REMIK", "REMIS", "REMPA", "REMPAH", "REMPAK", "REMPANG", "REMPAT", "REMUK", "REMUN", "RENANG", "RENCA", "RENCAK", "RENCANA", "RENCANG", "RENCEH", "RENCEK", "RENCET", "RENDAH", "RENDAM", "RENDANG", "RENDENG", "RENEK", "RENEM", "RENGAN", "RENGAT", "RENGGANG", "RENGGUT", "RENGIT", "RENGKA", "RENGKAH", "RENGKAM", "RENGKANG", "RENGKAP", "RENGKAT", "RENGKET", "RENGKOH", "RENGKOL", "RENGKONG", "RENGKUDAH", "RENGKUH", "RENGKUL", "RENGKUNG", "RENGKUP", "RENGRENG", "RENGUS", "RENGUT", "RENIK", "RENJANA", "RENJONG", "RENON", "RENOVASI", "RENTAK", "RENTAN", "RENTANG", "RENTAP", "RENTAS", "RENTENG", "RENTEN", "RENTEN", "RENTI", "RENUNG", "RENYAH", "RENYAI", "RENYAK", "RENYAM", "RENYAT", "RENYAU", "RENYEH", "RENYEM", "RENYUT", "REOT", "REPAH", "REPAK", "REPAS", "REPAT", "REPEH", "REPEK", "REPET", "REPIS", "REPOT", "REPUH", "REPUI", "REPUTASI", "RERAK", "RERES", "RESAH", "RESAK", "RESAM", "RESAN", "RESAP", "RESAT", "RESENSI", "RESEP", "RESEPSI", "RESERSE", "RESESI", "RESIKO", "RESIMEN", "RESITAL", "RESMI", "RESOLUSI", "RESPONS", "RESTORAN", "RESTU", "RESUME", "RETAK", "RETAL", "RETAS", "RETEH", "RETENSI", "RETET", "RETIH", "RETIS", "RETOK", "RETORIKA", "RETRET", "RETRIBUSI", "RETUR", "REUNI", "REWAK", "REWANG", "REWEL", "REZEKI", "REZIM", "RIAH", "RIAK", "RIAM", "RIAN", "RIANG", "RIAP", "RIBAT", "RIBU", "RIBUT", "RICAN", "RICAU", "RICIH", "RICIAN", "RICIK", "RICIS", "RICUH", "RIDAN", "RIDAT", "RIDIP", "RIHAL", "RIHAT", "RIJAL", "RIJANG", "RIJIT", "RIKUH", "RILES", "RILIS", "RIMAH", "RIMAR", "RIMBAS", "RIMBAT", "RIMBAU", "RIMBA", "RIMBUN", "RIMIS", "RIMPANG", "RIMPAS", "RIMPI", "RIMPIS", "RIMPUH", "RIMPUNG", "RINAI", "RINCAH", "RINCAU", "RINCI", "RINCIS", "RINDU", "RINGAN", "RINGGIT", "RINGIH", "RINGIK", "RINGIS", "RINGKAI", "RINGKAS", "RINGKIK", "RINGKING", "RINGKUK", "RINGKUS", "RINTANG", "RINTAS", "RINTIH", "RINTIK", "RINTIS", "RIPAK", "RIPUH", "RIRIK", "RIRIS", "RISALAH", "RISALAT", "RISAU", "RISET", "RISIKO", "RISIT", "RISKAN", "RITEL", "RITME", "RITUAL", "RIUK", "RIUNG", "RIVAL", "RIWAN", "RIWAYAT", "ROBAK", "ROBAT", "ROBEK", "ROBOH", "ROBOK", "ROBOT", "RONAH", "RONCE", "RONDA", "RONDO", "RONEO", "RONGGA", "RONGGANG", "RONGGENG", "RONGGOK", "RONGKONG", "RONGSOK", "RONTA", "RONTOK", "RONTGEN", "RUPIAH", "RURUH", "RURUP", "RUSUH", "RUSUK", "RUTIN", "RUYUNG", "SABAK", "SABANA", "SABANG", "SABAR", "SABAS", "SABDA", "SABEL", "SABEN", "SABET", "SABIL", "SABIT", "SABLON", "SABOTASE", "SABUK", "SABUN", "SABUR", "SABUT", "SADAH", "SADAI", "SADAK", "SADANG", "SADAP", "SADAR", "SADAU", "SADEL", "SADIK", "SADUR", "SAFARI", "SAFINAH", "SAFIR", "SAGAI", "SAGANG", "SAGAR", "SAGUER", "SAGUN", "SAHABAT", "SAHADA", "SAHAJA", "SAHAM", "SAHAN", "SAHAP", "SAHARA", "SAHAYA", "SAHID", "SAHIFA", "SAHIH", "SAHIR", "SAHUR", "SAHUT", "SAILO", "SAING", "SAINS", "SAJADAH", "SAJAK", "SAJANG", "SAJEN", "SAKAL", "SAKAR", "SAKARAT", "SAKAT", "SAKELAR", "SAKHALAT", "SAKHAWAT", "SAKHI", "SAKIT", "SAKLAR", "SAKRAL", "SAKRAMEN", "SAKRATUL", "SAKSI", "SAKTI", "SALAF", "SALAH", "SALAI", "SALAK", "SALAM", "SALANG", "SALAP", "SALAR", "SALAT", "SALDO", "SALEH", "SALEM", "SALEP", "SALIB", "SALIH", "SALIM", "SALIN", "SALING", "SALIP", "SALIR", "SALJU", "SALON", "SALUR", "SALUT", "SAMAD", "SAMAK", "SAMAN", "SAMAR", "SAMARA", "SAMAS", "SAMBAL", "SAMBAN", "SAMBAR", "SAMBAT", "SAMBAU", "SAMBEN", "SAMBET", "SAMBIL", "SAMBIT", "SAMBUT", "SAMPAH", "SAMPAI", "SAMPAK", "SAMPAN", "SAMPAR", "SAMPAS", "SAMPAT", "SAMPER", "SAMPIR", "SAMPIT", "SAMPO", "SAMPUL", "SAMUDRA", "SAMUM", "SAMUN", "SANAK", "SANAT", "SANATORIUM", "SANDANG", "SANDAR", "SANDAT", "SANDERA", "SANDIKALA", "SANDIWARA", "SANDUNG", "SANGA", "SANGAR", "SANGAT", "SANGGA", "SANGGAH", "SANGGAM", "SANGGAN", "SANGGAT", "SANGGER", "SANGGI", "SANGGIT", "SANGGUL", "SANGGUM", "SANGGUNG", "SANGKAH", "SANGKAK", "SANGKAL", "SANGKAN", "SANGKAR", "SANGKAT", "SANGKUT", "SANGKUR", "SANGLI", "SANGLU", "SANGON", "SANGSANG", "SANGSI", "SANITER", "SANJUNG", "SANKSI", "SANTAI", "SANTAK", "SANTAN", "SANTAP", "SANTASE", "SANTER", "SANTIR", "SANTRI", "SANTUN", "SAPAH", "SAPAI", "SAPAK", "SAPAN", "SAPAR", "SAPAT", "SAPAU", "SAPEH", "SAPEK", "SAPER", "SAPIR", "SAPIT", "SAPUT", "SARAF", "SARAK", "SARAN", "SARANG", "SARAP", "SARAT", "SARAU", "SAREH", "SAREN", "SARET", "SARGUT", "SARIKAN", "SARIP", "SARIRA", "SARIT", "SARJANA", "SARJU", "SARKA", "SARKASME", "SARKOFAGUS", "SARON", "SARS", "SARTAN", "SARTI", "SARTU", "SARUK", "SARUNG", "SARUT", "SARWA", "SASAK", "SASAL", "SASAN", "SASANA", "SASAP", "SASAR", "SASAT", "SASI", "SASTRA", "SASUL", "SATAI", "SATAK", "SATAR", "SATELIT", "SATIN", "SATIR", "SATRU", "SATUAN", "SATWA", "SAUDAGAR", "SAUDARA", "SAUDARI", "SAUK", "SAUM", "SAUN", "SAUNG", "SAUR", "SAWAH", "SAWAL", "SAWAN", "SAWANG", "SAWAT", "SAWER", "SAWIT", "SAWUT", "SAYAB", "SAYAD", "SAYAK", "SAYANG", "SAYAP", "SAYAT", "SAYET", "SAYID", "SAYUR", "SEBAB", "SEBAH", "SEBAI", "SEBAK", "SEBAL", "SEBAN", "SEBAR", "SEBAT", "SEBAU", "SEBAYANG", "SEBEK", "SEBENG", "SEBERANG", "SEBET", "SEBIH", "SEBIT", "SEBUK", "SEBUNG", "SEBUT", "SEBUYA", "SEDAH", "SEDAK", "SEDAM", "SEDAN", "SEDANG", "SEDAP", "SEDAR", "SEDARI", "SEDAT", "SEDEKAH", "SEDELINGGAM", "SEDENG", "SEDERHANA", "SEDIA", "SEDIKIT", "SEDIMEN", "SEDOT", "SEDUH", "SEGAH", "SEGAK", "SEGAL", "SEGAN", "SEGAR", "SEGARA", "SEGAT", "SEGEL", "SEGENAP", "SEGERA", "SEGMEN", "SEGOL", "SEHAT", "SEJAHTERA", "SEJARAH", "SEJUK", "SEKALI", "SEKARANG", "SEKOLAH", "SEKRETARIS", "SEKTOR", "SELALU", "SELAM", "SELAMAT", "SELANG", "SELARAS", "SELAT", "SELATAN", "SELEBRITI", "SELEKSI", "SELESAI", "SELISIH", "SELOKAN", "SELUAS", "SELUH", "SELUK", "SELUM", "SELUP", "SELUR", "SELUT", "SEMANGAT", "SEMANGKA", "SEMBAH", "SEMBAHYANG", "SEMBARANGAN", "SEMBILAN", "SEMBUH", "SEMBUNYI", "SEMEN", "SEMENTAR", "SEMESTA", "SEMINAR", "SEMPAT", "SEMPIT", "SEMPROTI", "SEMUA", "SEMUT", "SENANG", "SENAPAN", "SENAR", "SENDA", "SENDAWA", "SENDIRI", "SENDOK", "SENGAJA", "SENGAT", "SENGIT", "SENIMAN", "SENJATA", "SENTAK", "SENTER", "SENTIMEN", "SENTUH", "SENYUM", "SEPAK", "SEPATU", "SEPEDA", "SEPELE", "SEPIRING", "SEPULUH", "SEPUR", "SERAGAM", "SERAI", "SERAK", "SERAM", "SERAMBI", "SERANG", "SERAP", "SERAT", "SERAYU", "SERBA", "SERBET", "SERBU", "SERBUK", "SERDADU", "SEREAL", "SERET", "SERIKAT", "SERING", "SERIUS", "SERONOK", "SERTA", "SERTIFIKAT", "SERULING", "SERUM", "SESAH", "SESAK", "SESAL", "SESAMA", "SESAR", "SESAT", "SESUDAH", "SESUMBAR", "SETANG", "SETARA", "STASIUN", "STATUS", "STEMPEL", "SETIA", "SETUJU", "SIAMANG", "SIANG", "SIAPA", "SIASAT", "SIBUK", "SIDAK", "SIDANG", "SIDIK", "SIFAT", "SIGAP", "SIHIR", "SIKAP", "SIKAT", "SIKLUS", "SIKSA", "SILAKAN", "SILANG", "SILAP", "SILAT", "SILAU", "SILIH", "SILUET", "SILUMAN", "SIMAK", "SIMBAH", "SIMBOL", "SIMETRI", "SIMPANG", "SIMPATI", "SIMPAN", "SIMPEL", "SIMPUH", "SIMPUL", "SINAR", "SINDIKAT", "SINDIR", "SINERGI", "SINGGAH", "SINGKAP", "SINGKAT", "SINGKIR", "SINGKUR", "SINIS", "SINKRON", "SINTESIS", "SIPIL", "SIPIR", "SIPUT", "SIRAM", "SIRAT", "SIRINE", "SIRIP", "SIRKUIT", "SIRKULASI", "SIRNA", "SIRSAK", "SISIK", "SISIP", "SISIR", "SISTEM", "SISWA", "SITUASI", "SIUNG", "SIUR", "SKALA", "SKANDAL", "SKENARIO", "SKETSA", "SKRIPSI", "SOGOK", "SOKET", "SOLAT", "SOLEK", "SOLIDARITAS", "SOLUSI", "SOMBONG", "SOPAN", "SOPIR", "SORAK", "SOROT", "SOSIAL", "SOSIS", "SOSOK", "SPANDUK", "SPESIAL", "SPESIFIK", "SPION", "SPONSOR", "SPRINT", "STADION", "STANDAR", "STATISTIK", "STATUS", "STASIUN", "STERIL", "STIKER", "STRUKTUR", "STUDI", "STUDIO", "SUAKA", "SUAMI", "SUARA", "SUASANA", "SUATU", "SUBJEK", "SUBSIDI", "SUBSTANSI", "SUBUH", "SUBUR", "SUDAH", "SUDUT", "SUGIH", "SUGUH", "SUJUD", "SUKAR", "SUKARELA", "SUKSES", "SUKUR", "SULAM", "SULAP", "SULING", "SULIT", "SULTAN", "SULUH", "SULUNG", "SULUR", "SUMATERA", "SUMBANG", "SUMBAT", "SUMBER", "SUMBING", "SUMBU", "SUMPAH", "SUMPEK", "SUMPIT", "SUMSUM", "SUMUR", "SUNAT", "SUNGAI", "SUNGGING", "SUNGGUH", "SUNGKEM", "SUNGKUR", "SUNGUT", "SUNTING", "SUNTUK", "SUNTUK", "SUNYI", "SUPAYA", "SUPER", "SUPIR", "SURAH", "SURAI", "SURAM", "SURAT", "SURAU", "SUTAN", "SUUZON", "SWAFOTO", "SWALAYAN", "SWASTA", "SYAFAAT", "SYAHADAT", "SYAIR", "SYAMAN", "SYAMSI", "SYAMSIR", "SYARA", "SYARAF", "SYARAT", "SYARI", "SYARIAT", "SYARIF", "SYARIFAH", "SYARIK", "SYARIKAT", "SYATAR", "SYATIBI", "SYAWAL", "SYEKH", "SYIRIK", "SYIWA", "SYUKUR", "TAAT", "TABAH", "TABAK", "TABAL", "TABAN", "TABAR", "TABET", "TABIAT", "TABIB", "TABIK", "TABIR", "TABLOID", "TABRAK", "TABUH", "TABUN", "TABUNG", "TABUR", "TABUT", "TADAH", "TADAR", "TADARUS", "TADUNG", "TAFAKUR", "TAFSIR", "TAGAK", "TAGAL", "TAGAN", "TAGAR", "TAGEH", "TAGIH", "TAGUT", "TAHADI", "TAHAK", "TAHAN", "TAHANG", "TAHAP", "TAHAR", "TAHAT", "TAHAYUL", "TAHIAT", "TAHIL", "TAHIR", "TAHIS", "TAHIT", "TAHUN", "TAICI", "TAIFUN", "TAIKO", "TAKABUR", "TAKAD", "TAKAH", "TAKAK", "TAKAL", "TAKAN", "TAKAR", "TAKAT", "TAKBIR", "TAKDIR", "TAKEL", "TAKHTA", "TAKIK", "TAKIR", "TAKIS", "TAKJUB", "TAKKAN", "TAKLIM", "TAKLUK", "TAKMA", "TAKRAW", "TAKRIF", "TAKRIM", "TAKSA", "TAKSIR", "TAKSIS", "TAKTIK", "TAKTIS", "TAKUH", "TAKUK", "TAKUN", "TAKUT", "TAKWA", "TAKWIL", "TAKZIM", "TALAH", "TALAI", "TALAK", "TALAM", "TALAN", "TALANG", "TALAR", "TALAS", "TALAT", "TALAU", "TALEN", "TALENT", "TALENTA", "TALIB", "TALIS", "TALKUN", "TALUN", "TALUR", "TAMADUN", "TAMAH", "TAMAK", "TAMAM", "TAMAR", "TAMASYA", "TAMAT", "TAMBAH", "TAMBAK", "TAMBAL", "TAMBAN", "TAMBANG", "TAMBAR", "TAMBAT", "TAMBAT", "TAMBI", "TAMBO", "TAMBUL", "TAMBUN", "TAMBUNG", "TAMBUR", "TAMAT", "TAMENG", "TAMIS", "TAMPAH", "TAMPAK", "TAMPAN", "TAMPAR", "TAMPAS", "TAMPEH", "TAMPEL", "TAMPI", "TAMPIK", "TAMPIL", "TAMPIN", "TAMPIR", "TAMPIS", "TAMPOK", "TAMPUNG", "TAMSIL", "TAMUK", "TAMUN", "TANAI", "TANAK", "TANAM", "TANAT", "TANAU", "TANDAK", "TANDAN", "TANDANG", "TANDAS", "TANDAT", "TANDEM", "TANDES", "TANDUK", "TANDUN", "TANDUNG", "TANDUR", "TANGAH", "TANGAL", "TANGAP", "TANGAR", "TANGAS", "TANGAT", "TANGGA", "TANGGAH", "TANGGAL", "TANGGAP", "TANGGAR", "TANGGAS", "TANGGI", "TANGGUL", "TANGGUM", "TANGGUNG", "TANGIS", "TANGKAH", "TANGKAI", "TANGKAL", "TANGKAN", "TANGKAP", "TANGKAR", "TANGKAS", "TANGKAT", "TANGKE", "TANGKIL", "TANGKIS", "TANGKIT", "TANGKU", "TANGKUE", "TANGKUL", "TANGKUP", "TANGKUR", "TANGKUT", "TANGON", "TANGSA", "TANGSI", "TANIA", "TANIS", "TANJAK", "TANJAL", "TANJAN", "TANJAR", "TANJU", "TANJUNG", "TANJUR", "TANSI", "TANTANG", "TANTI", "TANTU", "TANUR", "TAPA", "TAPAH", "TAPAI", "TAPAK", "TAPAN", "TAPAR", "TAPAS", "TAPAU", "TAPEL", "TAPEK", "TAPER", "TAPIH", "TAPIK", "TAPIR", "TAPIS", "TAPIT", "TAPUK", "TAPUNG", "TAPUR", "TAPUS", "TARAF", "TARAH", "TARAI", "TARAK", "TARAM", "TARAN", "TARANG", "TARAP", "TARAS", "TARAT", "TARAU", "TAREKAT", "TAREK", "TARID", "TARIKH", "TARING", "TARIS", "TARGET", "TARIU", "TARKA", "TARKAS", "TARUH", "TARUK", "TARUM", "TARUNA", "TARUNG", "TARUP", "TARUS", "TASAH", "TASAK", "TASAMUH", "TASAN", "TASBIH", "TASDIK", "TASIK", "TASLIM", "TASMAK", "TASMIK", "TASRIF", "TASTAS", "TATAH", "TATAI", "TATAK", "TATAL", "TATAM", "TATAMI", "TATAN", "TATANG", "TATAP", "TATAR", "TATIH", "TATIT", "TATKALA", "TAUFAN", "TAUFIK", "TAUGE", "TAUHID", "TAUKE", "TAULADAN", "TAULAN", "TAULANY", "TAUM", "TAURAT", "TAWADUK", "TAWAH", "TAWAI", "TAWAK", "TAWAKAL", "TAWAN", "TAWANG", "TAWAS", "TAWAT", "TAYANG", "TAYAR", "TAYUM", "TAYUN", "TEATER", "TEBAH", "TEBAK", "TEBAL", "TEBAN", "TEBANG", "TEBAR", "TEBAS", "TEBAT", "TEBEH", "TEBEL", "TEBER", "TEBET", "TEBIH", "TEBIS", "TEBIT", "TEBOK", "TEBON", "TEBUS", "TECES", "TEDAS", "TEDENG", "TEDUH", "TEGAK", "TEGAL", "TEGANG", "TEGAP", "TEGAR", "TEGUH", "TEGUK", "TEGUR", "TEKAD", "TEKAH", "TEKAK", "TEKAP", "TEKAR", "TEKAT", "TEKEK", "TEKEL", "TEKEN", "TEKER", "TEKIS", "TEKLEK", "TEKNIK", "TEKNIS", "TEKNOLOGI", "TEKOH", "TEKOR", "TEKOS", "TEKTE", "TEKTITE", "TEKUA", "TEKUK", "TEKUL", "TEKUN", "TEKUP", "TEKUR", "TELAH", "TELADAN", "TELAGA", "TELAH", "TELAI", "TELAK", "TELAN", "TELANG", "TELANJANG", "TELANJUR", "TELANTAR", "TELAP", "TELAPAK", "TELAT", "TELATEN", "TELAU", "TELEDEK", "TELEGRAM", "TELEPON", "TELESKOP", "TELINGA", "TELITI", "TELOR", "TELUK", "TELUNGKUP", "TELUS", "TELUSUR", "TEMAH", "TEMALI", "TEMARANG", "TEMARAM", "TEMASA", "TEMATIK", "TEMBAK", "TEMBAKAU", "TEMBAKUL", "TEMBAM", "TEMBANG", "TEMBAR", "TEMBAS", "TEMBEH", "TEMBEL", "TEMBERANG", "TEMBIKAI", "TEMBILANG", "TEMBOLOK", "TEMBUNG", "TEMBUNI", "TEMBUS", "TEMEH", "TEMEN", "TEMET", "TEMON", "TEMPAH", "TEMPAI", "TEMPAK", "TEMPALA", "TEMPAN", "TEMPANG", "TEMPAR", "TEMPAS", "TEMPAT", "TEMPAYAN", "TEMPEL", "TEMPELENG", "TEMPERAMEN", "TEMPERATUR", "TEMPIK", "TEMPIL", "TEMPINIS", "TEMPOYAK", "TEMPUA", "TEMPUH", "TEMPUN", "TEMPUR", "TEMPURUNG", "TEMUI", "TEMUKU", "TEMUN", "TEMUT", "TENAGA", "TENANG", "TENDANG", "TENDAS", "TENDER", "TENGAK", "TENGAL", "TENGAR", "TENGAT", "TENGGAK", "TENGGANG", "TENGGARA", "TENGGEK", "TENGGELAM", "TENGGER", "TENGGILING", "TENGGOROK", "TENGKAR", "TENGKING", "TENGKU", "TENGKUK", "TENGKURAP", "TENGKURUP", "TENGU", "TENJET", "TENSI", "TENUN", "TENUNG", "TEOLOGI", "TEPAH", "TEPAK", "TEPAN", "TEPAS", "TEPEH", "TEPEK", "TEPER", "TEPIS", "TEPOK", "TEPUK", "TEPUNG", "TEPUS", "TERAH", "TERAI", "TERAJANG", "TERAK", "TERAN", "TERANG", "TERAP", "TERASI", "TERAT", "TERATAI", "TERAU", "TERAWANG", "TERBERAK", "TERBIT", "TERBUS", "TERCECER", "TERDEDAH", "TERDEPAN", "TERDIDIK", "TERENDAM", "TERENTANG", "TERIAK", "TERIGA", "TERIMA", "TERJANG", "TERJUN", "TERKAM", "TERKAP", "TERKAIT", "TERLANJUR", "TERLANTAR", "TERMINAL", "TERNAK", "TEROBOS", "TEROMPAH", "TEROMPET", "TEROPONG", "TEROWONGAN", "TERPERANJAT", "TERTAWA", "TERTENTU", "TERUNA", "TETAPI", "TETAS", "TETER", "TETES", "TETUA", "TEWAS", "TIADA", "TIARAP", "TIDAK", "TIKAM", "TIKAR", "TIKET", "TIKIS", "TIKIT", "TIKUS", "TILAM", "TILAN", "TILAP", "TILAS", "TILAWAT", "TILIK", "TIMAH", "TIMANG", "TIMBAL", "TIMBANG", "TIMBAU", "TIMBI", "TIMBIL", "TIMBUN", "TIMBUL", "TIMBUR", "TIMIT", "TIMPA", "TIMPAL", "TIMPANG", "TIMPAS", "TIMPI", "TIMPUS", "TIMUN", "TIMUS", "TINDAK", "TINDAS", "TINDIH", "TINDIS", "TINGGAL", "TINGGUNG", "TINGKAH", "TINGKAL", "TINGKAP", "TINGKAT", "TINGKEPI", "TINGKIL", "TINGKIR", "TINGKIS", "TINGKUH", "TINJAU", "TINJU", "TIONGHOA", "TIPAK", "TIPAR", "TIPAS", "TIPES", "TIPIS", "TIPUS", "TIRAH", "TIRAM", "TIRAN", "TIRAS", "TIRAT", "TIRIS", "TIRUS", "TISAK", "TISIK", "TISIN", "TISTIS", "TITAH", "TITIK", "TITIP", "TITIR", "TITIS", "TITIT", "TITRAT", "TITULER", "TIUNG", "TIWUL", "TOBAK", "TOBAT", "TOBEL", "TOBLOS", "TODONG", "TOGOG", "TOHOR", "TOJOK", "TOKAK", "TOKEK", "TOKOK", "TOKONG", "TOKOP", "TOLAK", "TOLAN", "TOLAP", "TOLEH", "TOLERANSI", "TOLOK", "TOLOL", "TOLONG", "TOMAT", "TOMBAK", "TOMBOL", "TOMBONG", "TOMONG", "TOMPEL", "TONGGAK", "TONGKANG", "TONGKAT", "TONGKOL", "TONGKRONG", "TONGON", "TONGOS", "TONTON", "TOPAN", "TOPANG", "TOPDAL", "TOPEK", "TOPENG", "TOPIK", "TOPOGRAFI", "TOPONIMI", "TOPLES", "TOPONG", "TORAKS", "TOREH", "TOREK", "TORKHAS", "TORNADO", "TORPEDO", "TOTALITAS", "TOTOK", "TOTOL", "TOWAK", "TUALANG", "TUANG", "TUANKU", "TUBAN", "TUBERKULOSIS", "TUBRUK", "TUBUH", "TUDING", "TUDUH", "TUDUNG", "TUGAS", "TUHAN", "TUHUR", "TUJUAN", "TUJUH", "TUKAK", "TUKAL", "TUKAM", "TUKANG", "TUKAR", "TUKAS", "TUKAT", "TUKIK", "TUKIL", "TUKUL", "TUKUNG", "TUKUP", "TULAH", "TUALANG", "TUALAS", "TUALAT", "TULEN", "TULIS", "TULUS", "TUMAN", "TUMANG", "TUMBAK", "TUMBAL", "TUMBANG", "TUMBAS", "TUMBUH", "TUMBUK", "TUMIS", "TUMIT", "TUMOR", "TUMPAH", "TUMPAK", "TUMPANG", "TUMPAS", "TUMPAT", "TUMPENG", "TUMPES", "TUMPIL", "TUMPU", "TUMPUK", "TUMPUL", "TUMPUR", "TUNAI", "TUNAK", "TUNAM", "TUNAS", "TUNDA", "TUNDANG", "TUNDUK", "TUNDUN", "TUNGAU", "TUNGGAL", "TUNGGANG", "TUNGGING", "TUNGGIT", "TUNGGUL", "TUNGKAI", "TUNGKAK", "TUNGKAP", "TUNGKU", "TUNGKUL", "TUNGKUP", "TUNGKUS", "TUNJANG", "TUNJUK", "TUNJUNG", "TUNTAS", "TUNTUN", "TUNTUT", "TUPAI", "TURAP", "TURAS", "TURIS", "TURISME", "TURNAMEN", "TURNE", "TURUN", "TURUS", "TURUT", "TUSTEL", "TUSUK", "TUSTEL", "TUTON", "TUTUH", "TUTUK", "TUTUL", "TUTUP", "TUTUR", "UANG", "UBAH", "UBAN", "UBAT", "UBEL", "UBET", "UBIN", "UBIT", "UBRAK", "UBUN", "UBUR", "UCAP", "UCEK", "UCER", "UCIL", "UCUNG", "UDANG", "UDARA", "UDAT", "UDEK", "UDEL", "UDET", "UDIK", "UDUK", "UDUR", "UDUT", "UGAHARI", "UGET", "UGUT", "UJANA", "UJUD", "UJIAN", "UJUNG", "UKAS", "UKIK", "UKIR", "UKRIT", "UKUR", "ULAH", "ULAI", "ULAK", "ULAM", "ULAN", "ULANG", "ULAP", "ULAR", "ULAS", "ULAT", "ULEKAN", "ULEM", "ULER", "ULET", "ULIT", "ULUNG", "ULUP", "ULUR", "UMAT", "UMBAI", "UMBAK", "UMBAN", "UMBAR", "UMBAT", "UMBI", "UMBUK", "UMBUL", "UMBUN", "UMBUT", "UMPAN", "UMPAT", "UMPET", "UMPIL", "UMPUK", "UMPUN", "UMUM", "UMUR", "UMUT", "UNAK", " UNAM", "UNAN", "UNAR", "UNCANG", "UNCAT", "UNCE", "UNCUI", "UNDAK", "UNDAN", "UNDANG", "UNDAS", "UNDAT", "UNDEL", "UNDUH", "UNDUK", "UNDUL", "UNDUR", "UNGGAK", "UNGGAL", "UNGGANG", "UNGGAT", "UNGGUL", "UNGGUN", "UNGGUT", "UNGKAH", "UNGKAP", "UNGKIL", "UNGKIR", "UNGKIT", "UNGLAI", "UNGUM", "UNGUT", "UNIFURM", "UNIK", "UNIVERSITAS", "UNIVERSAL", "UNJUK", "UNJUNG", "UNJUN", "UNJUT", "UNOK", "UNSANG", "UNSUR", "UNTAI", "UNTAL", "UNTANG", "UNTAR", "UNTAS", "UNTEL", "UNTIT", "UNTUNG", "UNTUK", "UNTUN", "UNTUT", "UPACARA", "UPAH", "UPAK", "UPAM", "UPAN", "UPAR", "UPAS", "UPAT", "UPAYA", "UPET", "UPETI", "UPIH", "UPIK", "UPIR", "UPIS", "UPIT", "UPOK", "URAI", "URAK", "URAM", "URAN", "URANG", "URAP", "URAS", "URAT", "URAU", "URAY", "URDU", "UREUM", "URGEN", "URIAN", "URIK", "URIL", "URIM", "URIN", "URIS", "URIT", "URUNG", "URUP", "URUS", "URUT", "URUY", "USAH", "USAHA", "USAK", "USAM", "USANG", "USAP", "USAT", "USIA", "USIK", "USIL", "USIR", "USKUP", "USUL", "USUNG", "USUS", "USUT", "UTAMA", "UTARA", "UTAS", "UTIH", "UTIK", "UTUH", "UTUS", "UVULA", "UZLAH", "UZUR", "VAKSIN", "VAKUM", "VALENSI", "VALID", "VALUTA", "VAMPIR", "VANILI", "VARIASI", "VARIETAS", "VASKULAR", "VELBET", "VELG", "VENA", "VENTILASI", "VENUS", "VERBAL", "VERIFIKASI", "VERMAK", "VERSI", "VERTEK", "VERTIKAL", "VETA", "VETERAN", "VETO", "VETSIN", "VIDEO", "VINIL", "VIOLA", "VIRUS", "VIRTUAL", "VISUAL", "VITAMIN", "VOKAL", "VOKASI", "VOLUME", "VONIS", "VOTUM", "VULGAR", "VULKANIS", "WAADAT", "WABAH", "WACANA", "WADAH", "WADAK", "WADAL", "WADAM", "WADANG", "WADAS", "WADAT", "WADUK", "WADUNG", "WAFAT", "WAHAH", "WAHAI", "WAHAM", "WAHANA", "WAHYU", "WAISYA", "WAIT", "WAJAH", "WAJAN", "WAJAR", "WAJIB", "WAJIK", "WAKAF", "WAKIL", "WAKTU", "WAKUN", "WALAD", "WALAFIAT", "WALAKA", "WALANG", "WALAU", "WALAWAFIAT", "WALET", "WALIMAHAN", "WALIMATUL", "WALISONGO", "WALKIE", "WALLAHU", "WALUH", "WANDA", "WANGI", "WANGUN", "WANITA", "WANODYA", "WANTER", "WAQAF", "WARA", "WARAK", "WARANGAN", "WARAS", "WARGA", "WARIA", "WARID", "WARIS", "WARISAN", "WARKAT", "WARNA", "WARNASARI", "WAROK", "WARSA", "WARTA", "WARTAWAN", "WARTEL", "WARUNG", "WASAK", "WASALAM", "WASANGKA", "WASIAT", "WASIL", "WASILAH", "WASIT", "WASLAP", "WASPADA", "WASWAS", "WATAK", "WATAN", "WATAS", "WATES", "WATUN", "WAWANCARA", "WAWAS", "WAWASAN", "WAYANG", "WAYUH", "WEDANA", "WEDANG", "WEDAR", "WEDEL", "WEDUK", "WEHER", "WEJANG", "WEKAS", "WEKEL", "WEKER", "WELANG", "WELAS", "WELAT", "WELIT", "WENANG", "WENAS", "WENDI", "WENGKU", "WENTER", "WERDA", "WERDI", "WERIT", "WERKUDARA", "WERST", "WORTEL", "WREDA", "WREDATAMA", "WUDU", "WUJUD", "WUKUF", "WULANG", "WULUNG", "WUNGU", "WUTUH", "XENIA", "XENOFOBIA", "XILOFON", "YAANI", "YABAI", "YABANI", "YADI", "YAHUD", "YAHUDI", "YAHUM", "YAITU", "YAKIN", "YAKIT", "YAKNI", "YAKSA", "YAKUB", "YAKUN", "YAKUT", "YAKUZA", "YAMAN", "YAMANI", "YANTRA", "YAPA", "YAPI", "YARAD", "YARA", "YASAN", "YASIN", "YASTI", "YATIM", "YAUMUL", "YAYASAN", "YAYI", "YAYU", "YOGA", "YOGI", "YOGYA", "YOHIMBINE", "YOJANA", "YOKER", "YOLAT", "YOYO", "YUDA", "YUDIKATIF", "YUDO", "YUDISIAL", "YUDISIUM", "YUGET", "YUGO", "YUNDA", "YUNANI", "YUNIOR", "YUNTA", "YURAN", "YURE", "YURIDIS", "YURIS", "YURISPRUDENSI", "YUTA", "ZABAD", "ZABAH", "ZABANIAH", "ZABARJAD", "ZABIB", "ZABIT", "ZABUR", "ZADAH", "ZAHID", "ZAHIR", "ZAITUN", "ZAKAT", "ZAKAR", "ZAKIR", "ZAKUM", "ZALIM", "ZALIR", "ZAMAN", "ZAMBAK", "ZAMRUD", "ZAMZAM", "ZANDA", "ZANGGI", "ZANI", "ZAPIN", "ZARAH", "ZAUJ", "ZAUJAH", "ZAYUN", "ZEBRA", "ZEBU", "ZENITH", "ZIARAH", "ZIG-ZAG", "ZIKIR", "ZILLULLAH", "ZINA", "ZINDIK", "ZINK", "ZIONISME", "ZIRAH", "ZIRKON", "ZODIAK", "ZONASI", "ZONK", "ZOOLOGI", "ZORBING", "ZUAMA", "ZUHAD", "ZUHUD", "ZUHUR", "ZULHAM", "ZULHIJAH", "ZULKAIDAH", "ZULMAT", "ZULU", "ZURAT", "ZURIAH", "SAAT", "SABAK", "SABAN", "SABANG", "SABAR", "SABAT", "SABDA", "SABEL", "SABEN", "SABET", "SABIL", "SABIT", "SABLON", "SABOT", "SABTU", "SABUK", "SABUN", "SABUR", "SABUT", "SADAH", "SADAI", "SADAK", "SADANG", "SADAP", "SADAR", "SADAU", "SADEL", "SADIK", "SADIN", "SADIR", "SADIS", "SADUR", "SAFARI", "SAFI", "SAFIR", "SAFRA", "SAFRAN", "SAGA", "SAGAI", "SAGAM", "SAGAN", "SAGAR", "SAGAS", "SAGO", "SAGON", "SAGU", "SAGUER", "SAHABAT", "SAHADAT", "SAHAJA", "SAHALA", "SAHAM", "SAHAN", "SAHAP", "SAHARA", "SAHAYA", "SAHDU", "SAHID", "SAHIFA", "SAHIH", "SAHIRA", "SAHITYA", "SAHUL", "SAHUR", "SAHUT", "SAIDI", "SAING", "SAINS", "SAIS", "SAIT", "SAJA", "SAJADAH", "SAJAK", "SAJAN", "SAJANG", "SAJAT", "SAJEN", "SAJI", "SAKA", "SAKAL", "SAKANG", "SAKAR", "SAKAT", "SAKAU", "SAKELAR", "SAKHI", "SAKHAWAT", "SAKIT", "SAKLAR", "SAKRAL", "SAKRAMEN", "SAKRAT", "SAKSI", "SAKTI", "SAKU", "SAKURA", "SALAF", "SALAH", "SALAI", "SALAK", "SALAM", "SALANG", "SALAP", "SALAR", "SALAT", "SALATIN", "SALDO", "SALEH", "SALEM", "SALEP", "SALIB", "SALIH", "SALIM", "SALIN", "SALING", "SALIP", "SALIR", "SALJU", "SALOME", "SALON", "SALP", "SALPING", "SALUR", "SALUT", "SAMA", "SAMAD", "SAMAK", "SAMAN", "SAMAR", "SAMBAR", "SAMBAT", "SAMBAU", "SAMBEL", "SAMBER", "SAMBIL", "SAMBIT", "SAMBO", "SAMBIT", "SAMBUNG", "SAMBUT", "SAMIR", "SAMPAH", "SAMPAI", "SAMPAK", "SAMPAN", "SAMPAR", "SAMPAS", "SAMPAT", "SAMPEAN", "SAMPER", "SAMPIR", "SAMPIT", "SAMPO", "SAMPUL", "SAMUDRA", "SAMUN", "SANA", "SANAK", "SANAT", "SANDANG", "SANDAR", "SANDAT", "SANDERA", "SANDI", "SANDUNG", "SANG", "SANGA", "SANGAM", "SANGAR", "SANGAT", "SANGGA", "SANGGAH", "SANGGAM", "SANGGAN", "SANGGAR", "SANGGAT", "SANGGER", "SANGGI", "SANGGIT", "SANGGUL", "SANGGUM", "SANGGUNG", "SANGKAH", "SANGKAK", "SANGKAL", "SANGKAN", "SANGKAR", "SANGKAT", "SANGKING", "SANGKU", "SANGKUR", "SANGKUT", "SANGSANG", "SANGSI", "SANGU", "SANI", "SANITER", "SANJUNG", "SANKSI", "SANO", "SANTAI", "SANTAK", "SANTAN", "SANTAP", "SANTAU", "SANTER", "SANTIR", "SANTRI", "SANTUN", "SAPA", "SAPAH", "SAPAI", "SAPAK", "SAPAN", "SAPAR", "SAPAT", "SAPAU", "SAPEH", "SAPEK", "SAPER", "SAPI", "SAPIR", "SAPIT", "SAPU", "SAPUT", "SARA", "SARAF", "SARAK", "SARAN", "SARANA", "SARANG", "SARAP", "SARAT", "SARAU", "SARE", "SAREH", "SAREN", "SARET", "SARI", "SARIKAN", "SARIP", "SARIRA", "SARIT", "SARJANA", "SARJU", "SARKAS", "SARON", "SARS", "SARTAN", "SARU", "SARUK", "SARUNG", "SARUT", "SARWA", "SASA", "SASAK", "SASAL", "SASAN", "SASANA", "SASAP", "SASAR", "SASAT", "SASI", "SASTRA", "SASUL", "SATAI", "SATAK", "SATAR", "SATELIT", "SATIH", "SATIN", "SATIR", "SATRU", "SATU", "SATUAN", "SATWA", "SAUDAGAR", "SAUDARA", "SAUK", "SAUM", "SAUN", "SAUNG", "SAUR", "SAWAH", "SAWAI", "SAWAL", "SAWAN", "SAWANG", "SAWAT", "SAWER", "SAWI", "SAWIT", "SAWUT", "SAYA", "SAYAB", "SAYAD", "SAYAK", "SAYANG", "SAYAP", "SAYAT", "SAYET", "SAYID", "SAYU", "SAYUR", "SEBAB", "SEBAH", "SEBAI", "SEBAK", "SEBAL", "SEBAN", "SEBAR", "SEBAT", "SEBAU", "SEBAYANG", "SEBEK", "SEBENG", "SEBERANG", "SEBET", "SEBIH", "SEBIT", "SEBUK", "SEBUNG", "SEBUT", "SEDAH", "SEDAK", "SEDAM", "SEDAN", "SEDANG", "SEDAP", "SEDAR", "SEDAT", "SEDEKAH", "SEDENG", "SEDERHANA", "SEDIA", "SEDIH", "SEDIKIT", "SEDIMEN", "SEDOT", "SEDUH", "SEGAH", "SEGAK", "SEGAL", "SEGAN", "SEGAR", "SEGARA", "SEGAT", "SEGEL", "SEGENAP", "SEGERA", "SEGI", "SEGMEN", "SEGOL", "SEHAT", "SEJAHTERA", "SEJARAH", "SEJATI", "SEJUK", "SEKALI", "SEKARANG", "SEKAP", "SEKAT", "SEKEDAR", "SEKEN", "SEKER", "SEKIN", "SEKIP", "SEKOLAH", "SEKONGKOL", "SEKOP", "SEKOTENG", "SEKRESI", "SEKRET", "SEKRETARIS", "SEKS", "SEKSI", "SEKSUAL", "SEKTE", "SEKTOR", "SEKUL", "SEKULER", "SEKUTU", "SEL", "SELA", "SELADA", "SELAGI", "SELAJU", "SELAK", "SELALU", "SELAM", "SELAMA", "SELAMAT", "SELAMBA", "SELAN", "SELANG", "SELANGKANG", "SELAP", "SELAR", "SELARAS", "SELAT", "SELATAN", "SELAWAT", "SELE", "SELEKSI", "SELEKTIF", "SELEBRAS", "SELEBRITI", "SELEDRI", "SELEGURI", "SELEH", "SELEK", "SELEMPANG", "SELENDANG", "SELENGGARA", "SELENTANG", "SELEPA", "SELEPE", "SELERA", "SELESAI", "SELISIH", "SELIT", "SELOKAN", "SELON", "SELONONG", "SELOP", "SELOT", "SELUAR", "SELUBUNG", "SELUDANG", "SELUDUK", "SELUK", "SELULER", "SELULOID", "SELULOSE", "SELULU", "SELUM", "SELUP", "SELURUH", "SELUSUP", "SELUSUR", "SELUT", "SEMADI", "SEMAK", "SEMALAM", "SEMANGAT", "SEMANGKA", "SEMANTIK", "SEMAT", "SEMBAH", "SEMBAHYANG", "SEMBARANG", "SEMBAT", "SEMBELIH", "SEMBELIT", "SEMBER", "SEMBERANI", "SEMBERIP", "SEMBILAN", "SEMBILU", "SEMBIR", "SEMBOYAN", "SEMBRONO", "SEMBUH", "SEMBUL", "SEMBUNYI", "SEMBUR", "SEMEN", "SEMENA", "SEMENANJUNG", "SEMENDA", "SEMENGKEK", "SEMENTARA", "SEMERBAK", "SEMESTA", "SEMI", "SEMINAR", "SEMINARI", "SEMIR", "SEMOGA", "SEMOK", "SEMPER", "SEMPIT", "SEMPOA", "SEMPROT", "SEMPURNA", "SEMU", "SEMUA", "SEMUR", "SEMUT", "SEN", "SENA", "SENADA", "SENANDIKA", "SENANDUNG", "SENANG", "SENAP", "SENAPAN", "SENAR", "SENAT", "SENAWAT", "SENDA", "SENDAL", "SENDANG", "SENDAT", "SENDAWA", "SENDEL", "SENDENG", "SENDER", "SENDI", "SENDIRI", "SENDOK", "SENDU", "SENDUDUK", "SENDUNG", "SENG", "SENGAJA", "SENGAL", "SENGAM", "SENGAP", "SENGAT", "SENGAU", "SENGON", "SENGUK", "SENGUT", "SENI", "SENIMAN", "SENIN", "SENIOR", "SENJATA", "SENJUNG", "SENKA", "SENONOH", "SENTA", "SENTAK", "SENTANA", "SENTAP", "SENTARA", "SENTAUS", "SENTAUSA", "SENTER", "SENTERI", "SENTI", "SENTIMEN", "SENTING", "SENTONG", "SENTOSA", "SENTRA", "SENTRAL", "SENTUH", "SENTUL", "SENTUNG", "SENUK", "SENUR", "SENYAP", "SENYAP", "SENYUM", "SENYUN", "SEPAK", "SEPAKAT", "SEPAN", "SEPANJANG", "SEPANDUK", "SEPANG", "SEPASANG", "SEPAT", "SEPATU", "SEPEDA", "SEPELEH", "SEPENGGAL", "SEPER", "SEPERANGKAT", "SEPERSEPULUH", "SEPERTI", "SEPI", "SEPIH", "SEPUH", "SEPUL", "SEPULUH", "SEPURA", "SEPUR", "SEPUT", "SERA", "SERABUT", "SERADA", "SERAGAM", "SERAH", "SERAI", "SERAK", "SERAM", "SERAMBI", "SERAMPANG", "SERAN", "SERANA", "SERANDANG", "SERANG", "SERANGGA", "SERANGKAI", "SERANI", "SERANTA", "SERAP", "SERAPAH", "SERAT", "SERAU", "SERAWAK", "SERAWAN", "SERAYA", "SERBA", "SERBAK", "SERBAN", "SERBAT", "SERBET", "SERBU", "SERBUK", "SERDADU", "SERDAH", "SERDAK", "SERDAM", "SERDANG", "SERDAWA", "SERDI", "SERDIH", "SEREAL", "SEREBRAL", "SEREMONI", "SERENADE", "SERENDAH", "SERET", "SERGAP", "SERI", "SERIKAT", "SERING", "SERINGAI", "SERIT", "SERIUS", "SERKAH", "SERKAI", "SERKAP", "SERKUP", "SERLAH", "SERLOIN", "SERO", "SEROBOT", "SEROJA", "SEROK", "SEROKAN", "SERONOK", "SEROT", "SERPIH", "SERSAN", "SERTA", "SERTIFIKAT", "SERTU", "SERU", "SERUAK", "SERUAL", "SERUDI", "SERUDUK", "SERUIT", "SERULING", "SERUM", "SERUNAI", "SERUNDA", "SERUNDENG", "SERUNG", "SERUT", "SESAH", "SESAJEN", "SESAK", "SESAL", "SESAMA", "SESAP", "SESAR", "SESAT", "SESAWI", "SESEPUH", "SESI", "SESUAI", "SESUDAH", "SESUMBAR", "SET", "SETA", "SETABEL", "SETABIL", "SETADION", "SETAHUN", "SETAI", "SETAKA", "SETAKAR", "SETAL", "SETALA", "SETALI", "SETAMAN", "SETAN", "SETANG", "SETANGGI", "SETARA", "SETASIUN", "SETAT", "SETAWAR", "SETEBAL", "SETEGUK", "SETEL", "SETELA", "SETELAH", "SETEM", "SETEMPAT", "SETENGAH", "SETER", "SETERAP", "SETERU", "SETIA", "SETIAP", "SETIAWAN", "SETIK", "SETILA", "SETINGGI", "SETIP", "SETIR", "SETOP", "SETOR", "SETRA", "SETRAP", "SETU", "SETUJU", "SETUL", "SETUM", "SETUNG", "SETUP", "SEWA", "SEWAH", "SEWAL", "SEWAR", "SEWAT", "SI", "SIA", "SIAGA", "SIANG", "SIANGIT", "SIAP", "SIAPA", "SIAR", "SIASAT", "SIAT", "SIBAK", "SIBAR", "SIBAT", "SIBUK", "SIBUR", "SIBUTA", "SIDA", "SIDAK", "SIDANG", "SIDAT", "SIDIK", "SIFAT", "SIGAI", "SIGAK", "SIGAP", "SIGAR", "SIGASIR", "SIGAT", "SIGI", "SIGUNG", "SIHIR", "SIJIL", "SIKAP", "SIKARI", "SIKAT", "SIKSA", "SIKU", "SILA", "SILAH", "SILAM", "SILANG", "SILAP", "SILAT", "SILATURAHMI", "SILAU", "SILET", "SILIH", "SILIK", "SILIKON", "SILIR", "SILU", "SILUET", "SILUK", "SILUMAN", "SILUNG", "SILUT", "SIMAK", "SIMBAH", "SIMBAK", "SIMBAR", "SIMBAT", "SIMBOL", "SIMBUR", "SIMETRI", "SIMFONI", "SIMPAI", "SIMPAN", "SIMPANG", "SIMPATI", "SIMPEL", "SIMPLISIT", "SIMPU", "SIMPUH", "SIMPUL", "SIMPUR", "SIMUT", "SINAR", "SINAU", "SINDIKAT", "SINDIR", "SINDROM", "SINERGI", "SINGGAH", "SINGGASANA", "SINGIT", "SINGKA", "SINGKAK", "SINGKANG", "SINGKAP", "SINGKAT", "SINGKEH", "SINGKIL", "SINGKIR", "SINGKUR", "SINGLET", "SINGSAT", "SINGSING", "SINI", "SINIS", "SINJAL", "SINKRON", "SINODE", "SINONIM", "SINOPSIS", "SINTAKS", "SINTAL", "SINTESIS", "SINTING", "SINTIR", "SINTUA", "SINTUK", "SINTUM", "SINTUNG", "SINU", "SINUS", "SINYAL", "SINYO", "SIOMAI", "SIPAI", "SIPASAN", "SIPAT", "SIPIL", "SIPIR", "SIPIT", "SIPOA", "SIPOA", "SIPU", "SIPUH", "SIPUL", "SIPUT", "SIR", "SIRA", "SIRAH", "SIRAM", "SIRAP", "SIRAT", "SIRAUT", "SIRENE", "SIRIH", "SIRIK", "SIRIP", "SIRKAM", "SIRKOL", "SIRKUIT", "SIRKULASI", "SIRKUS", "SIRNA", "SIROP", "SIRSA", "SIRSAK", "SIRU", "SIRUP", "SIRUT", "SISA", "SISAL", "SISI", "SISIH", "SISIK", "SISIP", "SISIR", "SISTALTIK", "SISTEM", "SISWA", "SISWI", "SIT", "SITA", "SITAK", "SITAT", "SITER", "SITI", "SITIR", "SITRAT", "SITUN", "SITU", "SITUASI", "SIUK", "SIUL", "SIUMAN", "SIUNG", "SIUR", "SIUT", "SIWAK", "SIWAL", "SIWER", "SIWALAN", "SKALA", "SKANDAL", "SKENARIO", "SKETSA", "SKORS", "SKRIPSI", "SOAL", "SOBAT", "SOBEK", "SOBOK", "SODA", "SODOK", "SODOR", "SOFA", "SOGO", "SOGOK", "SOHOR", "SOHWAT", "SOHIB", "SOHOR", "SOHUN", "SOJA", "SOK", "SOKA", "SOKER", "SOKET", "SOKO", "SOKONG", "SOL", "SOLA", "SOLAT", "SOLEK", "SOLENOID", "SOLID", "SOLIDER", "SOLO", "SOLOKAN", "SOLUM", "SOLUSI", "SOMASI", "SOMBOL", "SOMBOL", "SOMBONG", "SOMENGKEK", "SOMPILAN", "SOMPLAK", "SOMPOK", "SOMPRET", "SONAR", "SONATA", "SONDAK", "SONDEK", "SONDEL", "SONDER", "SONDOK", "SONDOL", "SONDONG", "SONETA", "SONGAR", "SONGEL", "SONGKET", "SONGKOK", "SONGONG", "SONIK", "SONO", "SONSONG", "SONTAK", "SONTOK", "SONTOLOYO", "SOP", "SOPAN", "SOPI", "SOPIR", "SOPRAN", "SORAK", "SORANG", "SORAT", "SORE", "SOREK", "SOREN", "SOROT", "SORP", "SORTIR", "SOSIAL", "SOSIALIS", "SOSOK", "SOSOR", "SOTO", "SOTOR", "SOYAK", "SPANDUK", "SPASI", "SPATULA", "SPESIAL", "SPESIFIK", "SPION", "SPIRIT", "SPONS", "SPONSOR", "SPORA", "SPORT", "SPORTIF", "SPOT", "SPRINT", "STADIUM", "STAF", "STAKA", "STALA", "STAL", "STAMIN", "STAMINA", "STANDAR", "STANZA", "START", "STASIUN", "STATIS", "STATISTIK", "STATISTIKA", "STATUS", "STEKER", "STEMPEL", "STENOGRAFI", "STENSIL", "STEPA", "STEREO", "STERIL", "STIKER", "STIMULAN", "STIMULUS", "STOK", "STOKER", "STOLA", "STOP", "STOPLES", "STRATA", "STRATEGI", "STRES", "STRIP", "STRUKTUR", "STUDI", "STUDIO", "SUA", "SUAI", "SUAKA", "SUAMI", "SUAMP", "SUAR", "SUARA", "SUASANA", "SUATU", "SUBAK", "SUBAL", "SUBAM", "SUBAN", "SUBANG", "SUBBAB", "SUBHAT", "SUBJEK", "SUBLIM", "SUBSIDI", "SUBSTANSI", "SUBUH", "SUBUR", "SUBVERSIF", "SUCI", "SUDA", "SUDAH", "SUDARA", "SUDARI", "SUDET", "SUDI", "SUDIP", "SUDRA", "SUDU", "SUDUK", "SUDUNG", "SUDUR", "SUDUT", "SUFAL", "SUFI", "SUFIKS", "SUGESTI", "SUGI", "SUGIH", "SUGUH", "SUGUL", "SUGUN", "SUH", "SUHAD", "SUHIAN", "SUHU", "SUHUF", "SUHUN", "SUIR", "SUJADAH", "SUJANA", "SUJEN", "SUJI", "SUJUD", "SUKA", "SUKAR", "SUKARELA", "SUKARIA", "SUKAT", "SUKET", "SUKI", "SUKMA", "SUKSES", "SUKSESI", "SUKU", "SUKUN", "SUKUR", "SULA", "SULAH", "SULAI", "SULALAT", "SULAM", "SULANG", "SULAP", "SULAR", "SULAWESI", "SULE", "SULER", "SULIT", "SULUH", "SULUK", "SULUNG", "SULUP", "SULUR", "SULUT", "SUMARAH", "SUMARAK", "SUMATERA", "SUMATRA", "SUMBA", "SUMBAH", "SUMBAK", "SUMBANG", "SUMBAR", "SUMBAT", "SUMBEL", "SUMBER", "SUMBI", "SUMBING", "SUMBU", "SUMBUL", "SUMBUNG", "SUMBUR", "SUMEDANG", "SUMEH", "SUMENG", "SUMING", "SUMIR", "SUMIT", "SUMPAH", "SUMPAL", "SUMPAN", "SUMPEK", "SUMPER", "SUMPIL", "SUMPIT", "SUMSUM", "SUMSUM", "SUMUR", "SUMUR", "SUNAH", "SUNAN", "SUNAT", "SUNATULLAH", "SUNDA", "SUNDAL", "SUNDANG", "SUNDEL", "SUNDUL", "SUNDUNG", "SUNGAI", "SUNGGA", "SUNGGI", "SUNGGING", "SUNGGUH", "SUNGKAN", "SUNGKAP", "SUNGKEM", "SUNGKIT", "SUNGKU", "SUNGKUR", "SUNGKUP", "SUNGKUR", "SUNGSUM", "SUNGU", "SUNGUT", "SUNU", "SUNUT", "SUNYI", "SUP", "SUPA", "SUPAYA", "SUPER", "SUPERIOR", "SUPIT", "SUPLEMEN", "SUPLIR", "SUPORT", "SUPRA", "SUPREMASI", "SURAH", "SURAI", "SURAM", "SURAT", "SURAU", "SUREL", "SURGA", "SURH", "SURIA", "SURIAN", "SURIH", "SURILI", "SURIS", "SURIT", "SURU", "SURUH", "SURUK", "SURUNG", "SURUP", "SURUT", "SURVAI", "SURVEI", "SUSAH", "SUSILA", "SUSPENSI", "SUSU", "SUSUH", "SUSUK", "SUSUL", "SUSUN", "SUSUP", "SUSUR", "SUSUT", "SUTAN", "SUTERA", "SUTIL", "SUTRA", "SUUN", "SUUZON", "SWAFOTO", "SWALAYAN", "SWARA", "SWASTA", "SWATANTRA", "SYABAS", "SYAFAAT", "SYAFIQ", "SYAH", "SYAHADAT", "SYAHDU", "SYAIR", "SYAITAN", "SYAL", "SYAMAN", "SYAMSI", "SYARA", "SYARAF", "SYARAT", "SYAREAT", "SYARI", "SYARIAT", "SYARIF", "SYARIFAH", "SYAUQ", "SYAWAL", "SYEKH", "SYUKUR", "SYUR", "TAALA", "TAAT", "TABAH", "TABAK", "TABAL", "TABAN", "TABAR", "TABAT", "TABEL", "TABET", "TABI", "TABIA", "TABIAT", "TABIB", "TABIK", "TABIR", "TABLIGH", "TABLO", "TABLOID", "TABOK", "TABRAK", "TABU", "TABUH", "TABUN", "TABUNG", "TABUR", "TABUT", "TADAH", "TADI", "TADIR", "TADARUS", "TADUNG", "TAFAKUR", "TAFSIR", "TAGAK", "TAGAL", "TAGAN", "TAGAR", "TAGEH", "TAGIH", "TAGUT", "TAHADI", "TAHAK", "TAHAN", "TAHANG", "TAHAP", "TAHAR", "TAHAT", "TAHAYUL", "TAHI", "TAHIAT", "TAHIL", "TAHIR", "TAHIS", "TAHIT", "TAHU", "TAHUN", "TAICI", "TAIFUN", "TAIKO", "TAIKUN", "TAIL", "TAILING", "TAIS", "TAJAK", "TAJAM", "TAJAP", "TAJAR", "TAJAU", "TAJI", "TAJIN", "TAJUK", "TAJUL", "TAJUR", "TAK", "TAKA", "TAKABUR", "TAKAD", "TAKAH", "TAKAK", "TAKAL", "TAKAN", "TAKAP", "TAKAR", "TAKAT", "TAKBIR", "TAKDIR", "TAKEL", "TAKHTA", "TAKI", "TAKIK", "TAKIR", "TAKIS", "TAKJUB", "TAKKAN", "TAKLIM", "TAKLUK", "TAKMA", "TAKRAW", "TAKRIF", "TAKRIM", "TAKSA", "TAKSIR", "TAKSIS", "TAKSI", "TAKTIK", "TAKTIS", "TAKUH", "TAKUK", "TAKUN", "TAKUT", "TAKWA", "TAKWIL", "TAKZIM", "TALAH", "TALAI", "TALAK", "TALAM", "TALAN", "TALANG", "TALAR", "TALAS", "TALAT", "TALAU", "TALEN", "TALENTA", "TALIB", "TALIK", "TALIM", "TALIS", "TALKUN", "TALUN", "TALUR", "TAM", "TAMADUN", "TAMAH", "TAMAK", "TAMAM", "TAMAN", "TAMAR", "TAMASYA", "TAMAT", "TAMBAH", "TAMBAK", "TAMBAL", "TAMBAN", "TAMBANG", "TAMBAR", "TAMBAT", "TAMBI", "TAMBO", "TAMBUL", "TAMBUN", "TAMBUNG", "TAMBUR", "TAMENG", "TAMIS", "TAMPAH", "TAMPAK", "TAMPAN", "TAMPAR", "TAMPAS", "TAMPEH", "TAMPEL", "TAMPI", "TAMPIK", "TAMPIL", "TAMPIN", "TAMPIR", "TAMPIS", "TAMPOK", "TAMPUNG", "TAMSIL", "TAMTAM", "TAMUK", "TAMUN", "TANAH", "TANAI", "TANAK", "TANAM", "TANAT", "TANAU", "TANDA", "TANDAK", "TANDAN", "TANDANG", "TANDAS", "TANDAT", "TANDEM", "TANDES", "TANDIK", "TANDING", "TANDU", "TANDUK", "TANDUN", "TANDUNG", "TANDUR", "TANG", "TANGAH", "TANGAL", "TANGAP", "TANGAR", "TANGAS", "TANGAT", "TANGGA", "TANGGAH", "TANGGAL", "TANGGAP", "TANGGAR", "TANGGAS", "TANGGI", "TANGGUH", "TANGGUK", "TANGGUL", "TANGGUM", "TANGGUNG", "TANGIS", "TANGKAH", "TANGKAI", "TANGKAL", "TANGKAN", "TANGKAP", "TANGKAR", "TANGKAS", "TANGKAT", "TANGKE", "TANGKEL", "TANGKI", "TANGKIL", "TANGKIS", "TANGKIT", "TANGKO", "TANGKU", "TANGKUE", "TANGKUL", "TANGKUP", "TANGKUR", "TANGKUT", "TANGON", "TANGSA", "TANGSI", "TANI", "TANIA", "TANIS", "TANJAK", "TANJAL", "TANJAN", "TANJAR", "TANJU", "TANJUNG", "TANJUR", "TANSI", "TANTANG", "TANTE", "TANTI", "TANTU", "TANUR", "TANYA", "TAPA", "TAPAH", "TAPAI", "TAPAK", "TAPAN", "TAPAR", "TAPAS", "TAPAU", "TAPEL", "TAPEK", "TAPER", "TAPI", "TAPIH", "TAPIK", "TAPIR", "TAPIS", "TAPIT", "TAPTU", "TAPUK", "TAPUNG", "TAPUR", "TAPUS", "TARAF", "TARAH", "TARAI", "TARAK", "TARAM", "TARAN", "TARANG", "TARAP", "TARAS", "TARAT", "TARAU", "TAREKAT", "TAREK", "TARI", "TARID", "TARIKH", "TARING", "TARIS", "TARGET", "TARIU", "TARKA", "TARKAS", "TARUH", "TARUK", "TARUM", "TARUNA", "TARUNG", "TARUP", "TARUS", "TAS", "TASAH", "TASAK", "TASAN", "TASBIH", "TASDIK", "TASIK", "TASLIM", "TASMAK", "TASMIK", "TASRIF", "TASTAS", "TATA", "TATAH", "TATAI", "TATAK", "TATAL", "TATAM", "TATAN", "TATANG", "TATAP", "TATAR", "TATIH", "TATIK", "TATIT", "TAU", "TAUFAN", "TAUFIK", "TAUGE", "TAUHID", "TAUKE", "TAULAN", "TAUM", "TAURAT", "TAUT", "TAWADUK", "TAWAH", "TAWAI", "TAWAK", "TAWAKAL", "TAWAN", "TAWANG", "TAWAS", "TAWAT", "TAWE", "TAWES", "TAWUR", "TAYANG", "TAYAR", "TAYUB", "TAYUM", "TAYUN", "TEATER", "TEBAH", "TEBAK", "TEBAL", "TEBAN", "TEBANG", "TEBAR", "TEBAS", "TEBAT", "TEBEH", "TEBEL", "TEBER", "TEBET", "TEBIH", "TEBIS", "TEBIT", "TEBOK", "TEBON", "TEBUS", "TECES", "TEDAS", "TEDENG", "TEDUH", "TEGAH", "TEGAK", "TEGAL", "TEGANG", "TEGAP", "TEGAR", "TEGAS", "TEGUH", "TEGUK", "TEGUR", "TEH", "TEKAD", "TEKAH", "TEKAK", "TEKAP", "TEKAR", "TEKAT", "TEKEK", "TEKEL", "TEKEN", "TEKER", "TEKIS", "TEKLOK", "TEKNIK", "TEKNIS", "TEKO", "TEKOH", "TEKOR", "TEKOS", "TEKTE", "TEKUA", "TEKUK", "TEKUL", "TEKUN", "TEKUP", "TEKUR", "TELA", "TELAH", "TELAGA", "TELAI", "TELAK", "TELAN", "TELANG", "TELAP", "TELAT", "TELAU", "TELENTANG", "TELEPON", "TELER", "TELESKOP", "TELEVISI", "TELITI", "TELOR", "TELUH", "TELUK", "TELUR", "TELUS", "TELUT", "TEMAH", "TEMALI", "TEMAM", "TEMAN", "TEMARA", "TEMARAM", "TEMAS", "TEMAT", "TEMAU", "TEMBAK", "TEMBAKAU", "TEMBAM", "TEMBANG", "TEMBAR", "TEMBAS", "TEMBEH", "TEMBEL", "TEMBER", "TEMBI", "TEMBUK", "TEMBUNG", "TEMBUNI", "TEMBUS", "TEMEH", "TEMEN", "TEMET", "TEMON", "TEMPA", "TEMPAH", "TEMPAI", "TEMPAK", "TEMPAN", "TEMPANG", "TEMPAR", "TEMPAS", "TEMPAT", "TEMPEL", "TEMPE", "TEMPEL", "TEMPIAR", "TEMPIK", "TEMPIL", "TEMPO", "TEMPUA", "TEMPUH", "TEMPUN", "TEMPUR", "TEMU", "TEMUKU", "TEMUN", "TEMUT", "TENAGA", "TENANG", "TENAR", "TENDA", "TENDANG", "TENDAS", "TENDER", "TENGAK", "TENGAL", "TENGAR", "TENGAT", "TENGGAK", "TENGGAN", "TENGGAR", "TENGGEK", "TENGGER", "TENGGING", "TENGGOROK", "TENGIK", "TENGIL", "TENGKAR", "TENGKING", "TENGKO", "TENGKU", "TENGKUK", "TENGKUR", "TENGU", "TENIS", "TENJET", "TENONG", "TENSI", "TENTU", "TENUN", "TENUNG", "TEORI", "TEP", "TEPAH", "TEPAK", "TEPAN", "TEPAS", "TEPEH", "TEPEK", "TEPER", "TEPI", "TEPIS", "TEPOK", "TEPUK", "TEPUNG", "TEPUS", "TERA", "TERAH", "TERAI", "TERAJANG", "TERAK", "TERAN", "TERANG", "TERAP", "TERAS", "TERAT", "TERATAI", "TERAU", "TERAWANG", "TERBANG", "TERBIT", "TERBUS", "TERI", "TERIAK", "TERIG", "TERIK", "TERIMA", "TERJANG", "TERJUN", "TERKA", "TERKAM", "TERKAP", "TERLALU", "TERMINAL", "TERNAK", "TEROBOS", "TERONG", "TEROPONG", "TERTAWA", "TERTIB", "TERUBUK", "TERUM", "TERUNA", "TERUNG", "TERUP", "TERUS", "TES", "TESIS", "TETAK", "TETAL", "TETAMP", "TETAP", "TETAPI", "TETAS", "TETER", "TETES", "TETUA", "TEWAS", "TIADA", "TIANG", "TIAP", "TIARAP", "TIBA", "TIBAN", "TIDAK", "TIDOR", "TIGA", "TIGEL", "TIHUL", "TIJAK", "TIK", "TIKA", "TIKAM", "TIKAR", "TIKET", "TIKIS", "TIKIT", "TIKU", "TIKUS", "TILAM", "TILAN", "TILAP", "TILAS", "TILIK", "TILUR", "TIM", "TIMAH", "TIMANG", "TIMBA", "TIMBAL", "TIMBANG", "TIMBAU", "TIMBI", "TIMBIL", "TIMBUL", "TIMBUN", "TIMBUR", "TIMIT", "TIMPA", "TIMPAL", "TIMPANG", "TIMPAS", "TIMPI", "TIMPUS", "TIMU", "TIMUN", "TIMUS", "TIN", "TINDAK", "TINDAS", "TINDIH", "TINDIS", "TINGGAL", "TINGGI", "TINGGUNG", "TINGKAH", "TINGKAL", "TINGKAP", "TINGKAT", "TINGKEPI", "TINGKIL", "TINGKIR", "TINGKIS", "TINGKUH", "TINJA", "TINJAU", "TINJU", "TINTA", "TIPAK", "TIPAR", "TIPAS", "TIPES", "TIPIS", "TIPU", "TIPUS", "TIRAH", "TIRAI", "TIRAM", "TIRAN", "TIRAS", "TIRAT", "TIRI", "TIRIS", "TIRU", "TIRUS", "TISAK", "TISIK", "TISIN", "TISTIS", "TITAH", "TITAR", "TITAY", "TITI", "TITIK", "TITIP", "TITIR", "TITIS", "TITIT", "TIUNG", "TIUP", "TIWUL", "TOBAK", "TOBAT", "TOBEL", "TOBLOS", "TODONG", "TOGA", "TOGOK", "TOHOR", "TOJOK", "TOK", "TOKAK", "TOKEK", "TOKO", "TOKOK", "TOKONG", "TOKOP", "TOLAK", "TOLAN", "TOLAP", "TOLEH", "TOLOK", "TOLOL", "TOLONG", "TOMA", "TOMAT", "TOMBAK", "TOMBOL", "TOMBONG", "TOMONG", "TOMPEL", "TONG", "TONGGAK", "TONGKANG", "TONGKAT", "TONGKOL", "TONGON", "TONGOS", "TONTON", "TOP", "TOPAN", "TOPANG", "TOPDAL", "TOPEK", "TOPENG", "TOPI", "TOPIK", "TOPONG", "TORAK", "TOREH", "TOREK", "TORKHAS", "TORNE", "TORPEDO", "TORSI", "TORTOR", "TOTAL", "TOTOK", "TOTOL", "TOWAK", "TUA", "TUAH", "TUAI", "TUAK", "TUAL", "TUALANG", "TUAN", "TUANG", "TUANKU", "TUAT", "TUBA", "TUBAN", "TUBES", "TUBIN", "TUBIR", "TUBUH", "TUBUH", "TUBUN", "TUDING", "TUDUH", "TUDUNG", "TUGAL", "TUGAS", "TUGU", "TUH", "TUHAN", "TUHUR", "TUI", "TUJU", "TUJUH", "TUJUL", "TUKAK", "TUKAL", "TUKAM", "TUKANG", "TUKAR", "TUKAS", "TUKAT", "TUKIK", "TUKIL", "TUKUL", "TUKUNG", "TUKUP", "TULAH", "TULANG", "TULAR", "TULAT", "TULE", "TULEN", "TULI", "TULIS", "TULUS", "TUMA", "TUMAN", "TUMANG", "TUMBAK", "TUMBAL", "TUMBANG", "TUMBAS", "TUMBUH", "TUMBUK", "TUMIS", "TUMIT", "TUMOR", "TUMPAH", "TUMPAK", "TUMPANG", "TUMPAS", "TUMPAT", "TUMPENG", "TUMPES", "TUMPIL", "TUMPU", "TUMPUK", "TUMPUL", "TUMPUR", "TUNA", "TUNAI", "TUNAK", "TUNAM", "TUNAS", "TUNDA", "TUNDANG", "TUNDUK", "TUNDUN", "TUNGGU", "TUNGKA", "TUNGKAH", "TUNGKAI", "TUNGKAK", "TUNGKAP", "TUNGKU", "TUNGKUL", "TUNGKUP", "TUNGKUS", "TUNJANG", "TUNJUK", "TUNJUNG", "TUNTAS", "TUNTUN", "TUNTUT", "TUNU", "TUPAI", "TUR", "TURAL", "TURAN", "TURAP", "TURAS", "TURBA", "TURE", "TURI", "TURIS", "TURUN", "TURUS", "TURUT", "TUS", "TUSTEL", "TUSUK", "TUTUP", "TUTUR", "UAI", "UAK", "UAN", "UANG", "UAP", "UAR", "UBAH", "UBAN", "UBAR", "UBAT", "UBEK", "UBEL", "UBET", "UBIK", "UBIN", "UBIT", "UBRAK", "UBUR", "UCAP", "UCEK", "UCER", "UCIL", "UCU", "UDANG", "UDARA", "UDAT", "UDEK", "UDEL", "UDET", "UDIK", "UDU", "UDUK", "UDUR", "UDUT", "UGA", "UGAHARI", "UGAMA", "UGET", "UGUT", "UIK", "UIR", "UJA", "UJANA", "UJAR", "UJI", "UJUB", "UJUD", "UJUL", "UJUNG", "UKIK", "UKIR", "UKRIT", "UKUP", "UKUR", "ULAH", "ULAI", "ULAK", "ULAM", "ULAN", "ULANG", "ULAP", "ULAR", "ULAS", "ULAT", "ULE", "ULEK", "ULER", "ULET", "ULI", "ULIR", "ULUN", "ULUNG", "ULUP", "ULUR", "UMAH", "UMARA", "UMAT", "UMBAI", "UMBAK", "UMBAN", "UMBAR", "UMBAT", "UMBI", "UMBUK", "UMBUL", "UMBUN", "UMBUR", "UMBUT", "UMPAMA", "UMPAN", "UMPAT", "UMPET", "UMPIL", "UMPUK", "UMPUN", "UMUM", "UMUR", "UMUT", "UNAK", "UNAM", "UNAN", "UNAR", "UNCANG", "UNCAT", "UNCE", "UNCUI", "UNDA", "UNDAK", "UNDAN", "UNDANG", "UNDAS", "UNDAT", "UNDEL", "UNDUH", "UNDUK", "UNDUL", "UNDUR", "UNGAP", "UNGAR", "UNGAT", "UNGGAK", "UNGGAL", "UNGGANG", "UNGGAT", "UNGGEL", "UNGGI", "UNGGIT", "UNGGU", "UNGGUL", "UNGGUN", "UNGGUT", "UNGKAH", "UNGKAP", "UNGKIL", "UNGKIR", "UNGKIT", "UNGKUR", "UNGTI", "UNGU", "UNGUM", "UNGUN", "UNGUT", "UNI", "UNIK", "UNIT", "UNJA", "UNJAK", "UNJAL", "UNJAT", "UNJUK", "UNJUN", "UNJUT", "UNOK", "UNSANG", "UNSUR", "UNTA", "UNTAI", "UNTAL", "UNTANG", "UNTAR", "UNTAS", "UNTEL", "UNTIT", "UNTUK", "UNTUN", "UNTUNG", "UNTUT", "UNYAI", "UPACARA", "UPADANA", "UPAH", "UPAK", "UPAM", "UPAN", "UPAR", "UPAS", "UPAT", "UPAYA", "UPET", "UPETI", "UPIH", "UPIK", "UPIR", "UPIS", "UPIT", "UPOK", "URA", "URAI", "URAK", "URAM", "URAN", "URANG", "URAP", "URAS", "URAT", "URAU", "URAY", "URDO", "URDU", "UREK", "UREM", "URET", "URGEN", "URI", "URIAN", "URIK", "URIL", "URIM", "URIN", "URIS", "URIT", "URUK", "URUNG", "URUP", "URUS", "URUT", "URUY", "USAH", "USAHA", "USAK", "USAM", "USANG", "USAP", "USAR", "USAT", "USIA", "USAI", "USIK", "USIL", "USIR", "USKUP", "USREK", "USTAD", "USTADZ", "USUL", "USUNG", "USUR", "USUS", "USUT", "UTAH", "UTAI", "UTAMA", "UTAN", "UTARA", "UTAS", "UTIH", "UTIK", "UTUH", "UTUS", "UUD", "UVULA", "UYUP", "UZLAH", "UZUR", "VAK", "VAKANSI", "VAKSI", "VAKSIN", "VAKUM", "VALAS", "VALEN", "VALENSI", "VALID", "VALIS", "VALOR", "VALUTA", "VAMPIR", "VANA", "VANILI", "VARI", "VARIABEL", "VARIAN", "VARIASI", "VARIASI", "VARIETAS", "VARISES", "VARNA", "VAS", "VASKULAR", "VATER", "VATIKAN", "VAU", "VEGE", "VEGETAR", "VEKTOR", "VELBET", "VELG", "VENA", "VENDOR", "VENTIL", "VENTILASI", "VENUS", "VERBA", "VERBAL", "VERIFIKASI", "VERLAK", "VERMAK", "VERMES", "VERMUT", "VERNIK", "VERSI", "VERSET", "VERSTEK", "VERSTENG", "VERSU", "VERTEBRA", "VERTEX", "VERTIKAL", "VESPA", "VETA", "VETER", "VETERAN", "VETO", "VETSIN", "VIA", "VIADUK", "VIAL", "VIBRASI", "VIDEO", "VIDIO", "VIGNETTE", "VIHARA", "VIKING", "VILA", "VIMPLER", "VINAL", "VINET", "VINIL", "VINYET", "VIOLA", "BIOLA", "BIOL", "BIOPSI", "BIR", "BIRA", "BIRAH", "BIRAI", "BIRAM", "BIRAMA", "BIRANG", "BIRAS", "BIRAT", "BIRD", "VIREO", "VIRGIN", "VIRGO", "VIRID", "VIRIL", "VIROLOGI", "VIRTU", "VIRTUAL", "VIRTUOSI", "VIRULEN", "VIRUS", "VISA", "VISI", "VISIBEL", "VISIKU", "VISIONER", "VISIT", "VISITEM", "VISITING", "VISITOR", "VISTA", "VISUAL", "VITAL", "VITALITAS", "VITAMIN", "VIVA", "VIVI", "VIVIPAR", "VLAK", "VLOG", "VOBLA", "VODA", "VODKA", "VOKAL", "VOKALIS", "VOKASI", "VOKAT", "VOKATIF", "VOLATIL", "VOLI", "VOLT", "VOLTA", "VOLTASE", "VOLUM", "VOLUME", "VONIS", "VORTEKS", "VOTUM", "VOVER", "VROOM", "VULGAR", "VULKAN", "VULKANIS", "VULKANISIR", "VULVA", "WAADAT", "WABAH", "WABAK", "WACANA", "WADAH", "WADAK", "WADAL", "WADAM", "WADANG", "WADAS", "WADAT", "WADAU", "WADUK", "WADUNG", "WAFAT", "WAGON", "WAH", "WAHAH", "WAHAI", "WAHAM", "WAHANA", "WAHAR", "WAHID", "WAHON", "WAHYU", "WAI", "WAISYA", "WAIT", "WAJAH", "WAJAN", "WAJAR", "WAJIB", "WAJIK", "WAJIT", "WAKA", "WAKAF", "WAKIL", "WAKTU", "WAKUN", "WALAD", "WALAFIAT", "WALAH", "WALAKA", "WALANG", "WALAT", "WALAU", "WALE", "WALET", "WALI", "WALIMAH", "WALIMATUL", "WALISONGO", "WALKER", "WALKIE", "WALLAH", "WALLAHU", "WALPA", "WALTER", "WALUH", "WALUKU", "WAN", "WANDA", "WANG", "WANGI", "WANGKANG", "WANGSA", "WANGUN", "WANITA", "WANODYA", "WANRA", "WANTA", "WANTER", "WAQAF", "WARA", "WARAK", "WARANGAN", "WARAS", "WARAT", "WARDA", "WARDI", "WARGA", "WARIA", "WARID", "WARIS", "WARISAN", "WARKAT", "WARNA", "WARNASARI", "WAROK", "WARSA", "WARTA", "WARTAWAN", "WARTEL", "WARUNG", "WASAK", "WASALAM", "WASANGKA", "WASBAK", "WASE", "WASEK", "WASI", "WASIAT", "WASIL", "WASILAH", "WASIR", "WASIT", "WASLAH", "WASLAP", "WASPADA", "WASWAS", "WAT", "WATAK", "WATAN", "WATAS", "WATES", "WATT", "WATUN", "WAWANCARA", "WAWAS", "WAWASAN", "WAY", "WAYANG", "WAYUH", "WE", "WEDANA", "WEDANG", "WEDAR", "WEDATAMA", "WEDEL", "WEDI", "WEDUK", "WEHER", "WEJANG", "WEKA", "WEKAS", "WEKEL", "WEKER", "WELANG", "WELAS", "WELAT", "WELIT", "WELUT", "WENANG", "WENAS", "WENDI", "WENGKU", "WENTER", "WERA", "WERDA", "WERDI", "WERIT", "WERKUDARA", "WERST", "WERT", "WES", "WESEL", "WESKET", "WESTER", "WET", "WETAN", "WEWE", "WIAYA", "WIBAWA", "WICARA", "WICU", "WIDA", "WIDADA", "WIDAK", "WIDANG", "WIDARA", "WIDURI", "WIDYAISWARA", "WIHARA", "WIJAYA", "WIJAYAKUSUMA", "WIJEN", "WIKA", "WILADAH", "WILAYAH", "WILAYAT", "WILIS", "WIMANA", "WINAYA", "WINDU", "WINGIT", "WINGLET", "WIRA", "WIRAMA", "WIRANG", "WIRASA", "WIRASTA", "WIRATAMA", "WIRAWAN", "WIRI", "WIRID", "WIRON", "WIRU", "WISATA", "WISATAWAN", "WISAYA", "WISIK", "WISUDA", "WISUDAWAN", "WITA", "WITIR", "WIWAHA", "WIWEKA", "WIWIT", "WIZURAI", "WOL", "WOLANDA", "WOLFRAM", "WONDER", "WONG", "WORTEL", "WREDA", "WREDATAMA", "WUDU", "WUJUD", "WUKUF", "WULANG", "WULUNG", "WUNGU", "WUTUH", "XENIA", "XENOFOBIA", "XENON", "XEROGRAFI", "XEROKS", "XILEM", "XILOFON", "YA", "YAANI", "YABAI", "YABANI", "YADI", "YAHAD", "YAHUD", "YAHUDI", "YAHUM", "YAITU", "YAKIN", "YAKIT", "YAKNI", "YAKSA", "YAKUB", "YAKUN", "YAKUT", "YAKUZA", "YAM", "YAMAN", "YAMANI", "YAMIN", "YANG", "YANTRA", "YAPA", "YAPI", "YARAD", "YARA", "YASAN", "YASIN", "YASTI", "YATIM", "YAUM", "YAUMUL", "YAYASAN", "YAYI", "YAYU", "YOGA", "YOGI", "YOGYA", "YOHIMBINE", "YOJANA", "YOKER", "YOLAT", "YOYO", "YUDA", "YUDIKATIF", "YUDISIAL", "YUDISIUM", "YUGET", "YUGO", "YUNDA", "YUNANI", "YUNIOR", "YUNTA", "YURAN", "YURE", "YURIDIS", "YURIS", "YURISDIKSI", "YURISPRUDENSI", "YUTA", "YUWANA", "YUYU", "ZABAD", "ZABAH", "ZABANIAH", "ZABARJAD", "ZABIB", "ZABIT", "ZABUR", "ZADAH", "ZAHID", "ZAHIR", "ZAITUN", "ZAKAT", "ZAKAR", "ZAKIR", "ZAKUM", "ZALIM", "ZALIR", "ZAMAN", "ZAMBAK", "ZAMRUD", "ZAMZAM", "ZANDA", "ZANGGI", "ZANI", "ZAPIN", "ZARAH", "ZAUJ", "ZAUJAH", "ZAYUN", "ZEBRA", "ZEBU", "ZEN", "ZENITH", "ZIARAH", "ZIG-ZAG", "ZIKIR", "ZILLULLAH", "ZINA", "ZINDIK", "ZINK", "ZIONISME", "ZIRAH", "ZIRKON", "ZODIAK", "ZONASI", "ZONK", "ZOOLOGI", "ZORBING", "ZUAMA", "ZUHAD", "ZUHUD", "ZUHUR", "ZULHAM", "ZULHIJAH", "ZULKAIDAH", "ZULMAT", "ZULU", "ZURAT", "ZURIAH"

}

-- Map Huruf Terdekat untuk Typo Natural
local NearKeys = {
    A={"S","Q","Z"}, S={"A","D","W","X"}, D={"S","F","E","C"}, F={"D","G","R","V"},
    G={"F","H","T","B"}, H={"G","J","Y","N"}, J={"H","K","U","M"}, K={"J","L","I"},
    L={"K","O","P"}, Q={"W","A"}, W={"Q","E","S"}, E={"W","R","D"}, R={"E","T","F"},
    T={"R","Y","G"}, Y={"T","U","H"}, U={"Y","I","J"}, I={"U","O","K"}, O={"I","P","L"},
    P={"O","L"}, Z={"X","A"}, X={"Z","C","S"}, C={"X","V","D"}, V={"C","B","F"},
    B={"V","N","G"}, N={"B","M","H"}, M={"N","J","K"}
}

local Config = {
    AutoActive = false,
    ESPEnabled = false,
    ContinuationOnly = true,
    LengthMode = "Normal (Acak)",
    TrapMode = true,
    TrapDifficulty = "Extreme (X, V, Z, Q)",
    TypingSpeed = 0.05,
    DelayBeforeType = 0.4,
    RetryDelay = 3.0,
    TypoChance = 5,
    AntiAFK = true,
    AFKFarm = false,
    SavedCFrame = nil,
    TargetUIName = "",
    Blacklist = {"ZAT", "SKOR", "SCORE", "MENU", "WAKTU", "TIME", "LEVEL", "RANK", "RECORD", "TEAM", "REWARDS", "PLAYERS", "ROUND", "SETTINGS", "BACK", "CLOSE", "EXIT", "BUY", "SELL", "PURCHASED", "PURCHASE", "BUY NOW", "CONFIRM", "CANCEL", "LOADING", "WAIT"},
    ShowLogs = true
}

local State = {
    UsedWords = {},
    IndexedDB = {},
    LastPromptRaw = "",
    CurrentMatches = {},
    MatchIndex = 1,
    IsBusy = false,
    LastTryTime = 0,
    CountUsed = 0
}

local TrapDict = {
    ["Extreme (X, V, Z, Q)"] = {X=true, V=true, Z=true, Q=true},
    ["Hard (F, W, Y)"] = {F=true, W=true, Y=true},
    ["Medium (J, P, G)"] = {J=true, P=true, G=true}
}

-- ==================== FUNGSI LOGGING ====================
local function log(msg, isError)
    if Config.ShowLogs then
        if isError then
            warn("[SAMBUNG KATA] " .. msg)
        else
            print("[SAMBUNG KATA] " .. msg)
        end
    end
end

-- ==================== FUNGSI INDEX DATABASE ====================
local function rebuildIndex()
    State.IndexedDB = {}
    for _, word in ipairs(kataKBBI) do
        local upper = word:upper()
        local first = upper:sub(1,1)
        if not State.IndexedDB[first] then State.IndexedDB[first] = {} end
        table.insert(State.IndexedDB[first], upper)
    end
    log("Database di-rebuild, total kata: " .. #kataKBBI)
end
rebuildIndex()

-- ==================== FUNGSI UTILITAS ====================
local function forceClear()
    for i = 1, 20 do
        VIM:SendKeyEvent(true, Enum.KeyCode.Backspace, false, game)
        task.wait(0.005)
        VIM:SendKeyEvent(false, Enum.KeyCode.Backspace, false, game)
    end
end

local function cleanText(str)
    if not str then return "" end
    local cleaned = str:gsub("<[^>]+>", "")
    cleaned = cleaned:gsub("%s+", " ")
    return cleaned
end

-- Ekstrak prefix dari teks (hanya 1-3 huruf)
local function extractPrefix(teks)
    teks = cleanText(teks):upper()
    -- Cari setelah titik dua
    local prefix = teks:match(":[%s]*([%a]+)")
    if prefix then
        if #prefix <= 3 then
            log("Prefix ditemukan via titik dua: " .. prefix)
            return prefix
        else
            log("Setelah titik dua terlalu panjang (" .. #prefix .. "), diabaikan: " .. prefix)
        end
    end
    -- Coba ambil kata terakhir jika panjang <= 3
    local words = {}
    for w in teks:gmatch("%a+") do
        table.insert(words, w)
    end
    if #words > 0 then
        local last = words[#words]
        if #last <= 3 then
            log("Prefix ditemukan via kata pendek: " .. last)
            return last
        end
    end
    log("Tidak ada prefix dalam teks: " .. teks, true)
    return nil
end

local function get5Options(awalan)
    awalan = awalan:upper()
    local firstLetter = awalan:sub(1,1)
    local candidates = State.IndexedDB[firstLetter] or {}
    local validWords = {}
    
    for _, kata in ipairs(candidates) do
        if kata:sub(1, #awalan) == awalan and not State.UsedWords[kata] and #kata > #awalan then
            table.insert(validWords, kata)
        end
    end

    if Config.LengthMode == "Sombong (Panjang)" then
        table.sort(validWords, function(a, b) return #a > #b end)
    elseif Config.LengthMode == "Cepat (Pendek)" then
        table.sort(validWords, function(a, b) return #a < #b end)
    else
        for i = #validWords, 2, -1 do
            local j = math.random(i)
            validWords[i], validWords[j] = validWords[j], validWords[i]
        end
    end

    local finalResults = {}
    local activeTraps = TrapDict[Config.TrapDifficulty] or {}
    if Config.TrapMode then
        for i = #validWords, 1, -1 do
            if activeTraps[validWords[i]:sub(-1)] then 
                table.insert(finalResults, {word = validWords[i], pref = awalan})
                table.remove(validWords, i)
            end
        end
    end
    for i=1, math.min(5 - #finalResults, #validWords) do
        table.insert(finalResults, {word = validWords[i], pref = awalan})
    end
    return finalResults
end

local function ketikOpsi(data)
    if State.IsBusy then return end
    State.IsBusy = true
    
    local word = data.word
    local pref = data.pref
    local toType = word
    
    if Config.ContinuationOnly and word:sub(1, #pref) == pref then
        toType = word:sub(#pref + 1)
        log("Mengetik sisa: " .. toType .. " (dari " .. word .. ")")
    else
        log("Mengetik full: " .. word)
    end

    forceClear()
    task.wait(Config.DelayBeforeType)

    for i = 1, #toType do
        local char = toType:sub(i, i)
        if math.random(1, 100) <= Config.TypoChance and NearKeys[char] then
            local wrong = NearKeys[char][math.random(#NearKeys[char])]
            VIM:SendKeyEvent(true, wrong, false, game)
            task.wait(0.05)
            VIM:SendKeyEvent(false, wrong, false, game)
            task.wait(0.1)
            VIM:SendKeyEvent(true, "Backspace", false, game)
            task.wait(0.05)
            VIM:SendKeyEvent(false, "Backspace", false, game)
        end
        VIM:SendKeyEvent(true, char, false, game)
        task.wait(Config.TypingSpeed)
        VIM:SendKeyEvent(false, char, false, game)
    end
    
    task.wait(0.1)
    VIM:SendKeyEvent(true, Enum.KeyCode.Return, false, game)
    VIM:SendKeyEvent(false, Enum.KeyCode.Return, false, game)
    
    State.UsedWords[word] = true
    State.CountUsed = State.CountUsed + 1
    State.LastTryTime = tick()
    log("Kata terkirim: " .. word .. " (total: " .. State.CountUsed .. ")")
    task.wait(1)
    State.IsBusy = false
end

-- ==================== ESP INTERAKTIF ====================
local ESPGui = Instance.new("ScreenGui")
ESPGui.Name = "SambungKataESP"
ESPGui.Parent = game.CoreGui
ESPGui.Enabled = false
local ESPFrame = Instance.new("Frame", ESPGui)
ESPFrame.Size = UDim2.new(0, 220, 0, 280)
ESPFrame.Position = UDim2.new(0.6, 0, 0.4, 0)
ESPFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 30)
ESPFrame.BorderSizePixel = 0
ESPFrame.Active = true
ESPFrame.Draggable = true
Instance.new("UICorner", ESPFrame).CornerRadius = UDim.new(0, 8)
local ESPTitle = Instance.new("TextLabel", ESPFrame)
ESPTitle.Size = UDim2.new(1, 0, 0, 35)
ESPTitle.Text = "💡 PILIH JAWABAN"
ESPTitle.TextColor3 = Color3.fromRGB(100, 255, 180)
ESPTitle.Font = Enum.Font.GothamBold
ESPTitle.BackgroundTransparency = 1
local ESPClose = Instance.new("TextButton", ESPFrame)
ESPClose.Size = UDim2.new(0, 30, 0, 30)
ESPClose.Position = UDim2.new(1, -35, 0, 5)
ESPClose.Text = "X"
ESPClose.TextColor3 = Color3.new(1,1,1)
ESPClose.BackgroundColor3 = Color3.fromRGB(200, 50, 50)
ESPClose.Font = Enum.Font.GothamBold
Instance.new("UICorner", ESPClose).CornerRadius = UDim.new(0, 15)
ESPClose.MouseButton1Click:Connect(function() ESPGui.Enabled = false end)

local ESPBtns = {}
for i = 1, 5 do
    local b = Instance.new("TextButton", ESPFrame)
    b.Size = UDim2.new(0.9, 0, 0, 35)
    b.Position = UDim2.new(0.05, 0, 0, 40 + (i * 40))
    b.BackgroundColor3 = Color3.fromRGB(40, 45, 60)
    b.TextColor3 = Color3.fromRGB(220, 220, 220)
    b.Font = Enum.Font.GothamSemibold
    b.Visible = false
    Instance.new("UICorner", b).CornerRadius = UDim.new(0, 6)
    b.MouseButton1Click:Connect(function()
        if State.CurrentMatches[i] and not State.IsBusy then
            ketikOpsi(State.CurrentMatches[i])
        end
    end)
    ESPBtns[i] = b
end

-- ==================== UI RAYFIELD ====================
local Window = Rayfield:CreateWindow({
    Name = "Sambung Kata | ULTIMATE V17.4",
    LoadingTitle = "Deteksi Akurat 1-3 Huruf",
    LoadingSubtitle = "by Enigma"
})

local DashTab = Window:CreateTab("📊 Dashboard")
local SetupTab = Window:CreateTab("🎯 Target Setup")
local AutoTab = Window:CreateTab("⚙️ Auto-Bot")
local TrapTab = Window:CreateTab("🪤 Trap Engine")
local HumTab = Window:CreateTab("⌨️ Typing")
local AFKTab = Window:CreateTab("💤 AFK Farm")
local DBTab = Window:CreateTab("📚 Database")

-- Dashboard
local LblDet = DashTab:CreateLabel("Terdeteksi: -")
local LblUsed = DashTab:CreateLabel("🔥 Kata digunakan: 0")
local LblStatus = DashTab:CreateLabel("Status: Idle")
local LblPrefix = DashTab:CreateLabel("Prefix terakhir: -")

DashTab:CreateButton({
    Name = "🔄 Update Status",
    Callback = function()
        LblDet:Set("Terdeteksi: " .. (State.LastPromptRaw or "-"))
        LblUsed:Set("🔥 Kata digunakan: " .. State.CountUsed)
        LblStatus:Set("Status: " .. (Config.AutoActive and "Aktif" or "Mati"))
        LblPrefix:Set("Prefix terakhir: " .. (State.LastPromptRaw or "-"))
    end
})

DashTab:CreateToggle({
    Name = "Tampilkan Log di Console",
    CurrentValue = true,
    Callback = function(v) Config.ShowLogs = v end
})

-- Target Setup
SetupTab:CreateButton({
    Name = "🔍 SCAN OTOMATIS (AKURAT)",
    Callback = function()
        for _, gui in ipairs(LP.PlayerGui:GetChildren()) do
            if gui:IsA("ScreenGui") and gui.Enabled then
                for _, obj in ipairs(gui:GetDescendants()) do
                    if (obj:IsA("TextLabel") or obj:IsA("TextButton")) and obj.Visible and obj.Text ~= "" then
                        local t = cleanText(obj.Text):upper()
                        -- Cek blacklist
                        local isBlacklisted = false
                        for _, bl in ipairs(Config.Blacklist) do
                            if t:find(bl) then isBlacklisted = true break end
                        end
                        if isBlacklisted then continue end
                        
                        -- Coba ekstrak prefix
                        local prefix = extractPrefix(t)
                        if prefix then
                            Config.TargetUIName = obj.Name
                            Rayfield:Notify({Title="Target ditemukan!", Content=obj.Name .. " : " .. t})
                            log("Target otomatis: " .. obj.Name .. " dengan prefix: " .. prefix)
                            return
                        end
                    end
                end
            end
        end
        Rayfield:Notify({Title="Tidak ditemukan", Content="Coba manual atau pastikan soal tampil"})
    end
})

SetupTab:CreateInput({
    Name = "Nama UI Manual",
    PlaceholderText = "Contoh: WordLabel",
    Callback = function(v)
        Config.TargetUIName = v
        log("Target manual: " .. v)
    end
})

-- Auto Bot
AutoTab:CreateToggle({
    Name = "▶️ AKTIFKAN BOT",
    CurrentValue = false,
    Callback = function(v) Config.AutoActive = v end
})

AutoTab:CreateToggle({
    Name = "🖱️ TAMPILKAN ESP",
    CurrentValue = false,
    Callback = function(v)
        Config.ESPEnabled = v
        ESPGui.Enabled = v
    end
})

AutoTab:CreateDropdown({
    Name = "Panjang Kata",
    Options = {"Normal (Acak)", "Sombong (Panjang)", "Cepat (Pendek)"},
    CurrentOption = {"Normal (Acak)"},
    Callback = function(v) Config.LengthMode = v[1] end
})

AutoTab:CreateSlider({
    Name = "Retry Delay (detik)",
    Range = {1, 5},
    Increment = 0.5,
    CurrentValue = 3,
    Callback = function(v) Config.RetryDelay = v end
})

AutoTab:CreateToggle({
    Name = "Hanya lanjutan (tanpa awalan)",
    CurrentValue = true,
    Callback = function(v) Config.ContinuationOnly = v end
})

-- Trap Engine
TrapTab:CreateToggle({
    Name = "Aktifkan Trap",
    CurrentValue = true,
    Callback = function(v) Config.TrapMode = v end
})

TrapTab:CreateDropdown({
    Name = "Kesulitan Trap",
    Options = {"Extreme (X, V, Z, Q)", "Hard (F, W, Y)", "Medium (J, P, G)"},
    CurrentOption = {"Extreme (X, V, Z, Q)"},
    Callback = function(v) Config.TrapDifficulty = v[1] end
})

-- Typing
HumTab:CreateSlider({
    Name = "Typo Chance (%)",
    Range = {0, 20},
    Increment = 1,
    CurrentValue = 5,
    Callback = function(v) Config.TypoChance = v end
})

HumTab:CreateSlider({
    Name = "Typing Speed (detik per huruf)",
    Range = {0.01, 0.2},
    Increment = 0.01,
    CurrentValue = 0.05,
    Callback = function(v) Config.TypingSpeed = v end
})

HumTab:CreateSlider({
    Name = "Delay sebelum ngetik",
    Range = {0.1, 1.0},
    Increment = 0.1,
    CurrentValue = 0.4,
    Callback = function(v) Config.DelayBeforeType = v end
})

-- AFK
AFKTab:CreateButton({
    Name = "📍 SAVE POSISI",
    Callback = function()
        if LP.Character and LP.Character:FindFirstChild("HumanoidRootPart") then
            Config.SavedCFrame = LP.Character.HumanoidRootPart.CFrame
            Rayfield:Notify({Title="Posisi tersimpan"})
            log("Posisi tersimpan")
        end
    end
})

AFKTab:CreateToggle({
    Name = "Auto-Teleport ke posisi",
    CurrentValue = false,
    Callback = function(v) Config.AFKFarm = v end
})

AFKTab:CreateToggle({
    Name = "Anti-AFK (virtual)",
    CurrentValue = true,
    Callback = function(v) Config.AntiAFK = v end
})

-- Database
DBTab:CreateButton({
    Name = "♻️ RESET MEMORY KATA TERPAKAI",
    Callback = function()
        State.UsedWords = {}
        State.CountUsed = 0
        LblUsed:Set("🔥 Kata digunakan: 0")
        Rayfield:Notify({Title="Memory direset"})
        log("Memory kata terpakai direset")
    end
})

DBTab:CreateButton({
    Name = "🔄 REBUILD INDEX",
    Callback = function()
        rebuildIndex()
        Rayfield:Notify({Title="Index database diperbarui", Content="Total: " .. #kataKBBI})
    end
})

DBTab:CreateInput({
    Name = "Tambah Kata Baru",
    PlaceholderText = "Ketik kata...",
    Callback = function(v)
        if v ~= "" then
            table.insert(kataKBBI, v:upper())
            rebuildIndex()
            Rayfield:Notify({Title="Kata ditambahkan"})
        end
    end
})

DBTab:CreateParagraph({
    Title = "Info Database",
    Content = "Jumlah kata saat ini: " .. #kataKBBI
})

-- ==================== ENGINE UTAMA ====================
task.spawn(function()
    while true do
        task.wait(0.3)
        if not (Config.AutoActive or Config.ESPEnabled) then
            LblStatus:Set("Status: Idle")
            continue
        end

        -- Cari target UI
        local targetUI = nil
        if Config.TargetUIName ~= "" then
            for _, gui in ipairs(LP.PlayerGui:GetChildren()) do
                if gui:IsA("ScreenGui") then
                    local found = gui:FindFirstChild(Config.TargetUIName, true)
                    if found and (found:IsA("TextLabel") or found:IsA("TextButton")) and found.Visible then
                        targetUI = found
                        break
                    end
                end
            end
        else
            -- Scan otomatis jika tidak ada nama
            for _, gui in ipairs(LP.PlayerGui:GetChildren()) do
                if gui:IsA("ScreenGui") and gui.Enabled then
                    for _, obj in ipairs(gui:GetDescendants()) do
                        if (obj:IsA("TextLabel") or obj:IsA("TextButton")) and obj.Visible and obj.Text ~= "" then
                            local t = cleanText(obj.Text):upper()
                            local isBlacklisted = false
                            for _, bl in ipairs(Config.Blacklist) do
                                if t:find(bl) then isBlacklisted = true break end
                            end
                            if isBlacklisted then continue end
                            if extractPrefix(t) then
                                targetUI = obj
                                break
                            end
                        end
                    end
                end
                if targetUI then break end
            end
        end

        if not targetUI then
            LblStatus:Set("Status: Mencari UI...")
            continue
        end

        -- Ambil prefix
        local prefix = extractPrefix(targetUI.Text)
        if not prefix then
            LblStatus:Set("Status: Tidak ada prefix")
            continue
        end

        LblDet:Set("Terdeteksi: " .. prefix)
        LblPrefix:Set("Prefix terakhir: " .. prefix)
        LblStatus:Set("Status: Memproses...")
        log("Prefix terdeteksi: " .. prefix)

        -- Update jika prefix baru
        if prefix ~= State.LastPromptRaw then
            State.LastPromptRaw = prefix
            State.MatchIndex = 1
            State.CurrentMatches = get5Options(prefix)
            log("Mendapatkan " .. #State.CurrentMatches .. " opsi untuk prefix " .. prefix)
            
            -- Update ESP
            if Config.ESPEnabled then
                for i=1, 5 do
                    if State.CurrentMatches[i] then
                        ESPBtns[i].Text = State.CurrentMatches[i].word
                        ESPBtns[i].Visible = true
                    else
                        ESPBtns[i].Visible = false
                    end
                end
            end
        end

        -- Auto answer jika aktif
        if Config.AutoActive and not State.IsBusy then
            if #State.CurrentMatches >= State.MatchIndex then
                ketikOpsi(State.CurrentMatches[State.MatchIndex])
                LblUsed:Set("🔥 Kata digunakan: " .. State.CountUsed)
            else
                State.MatchIndex = 1
                log("Tidak ada opsi lagi untuk prefix " .. prefix)
            end
        elseif Config.AutoActive and tick() - State.LastTryTime > Config.RetryDelay and #State.CurrentMatches > State.MatchIndex then
            State.MatchIndex = State.MatchIndex + 1
            if #State.CurrentMatches >= State.MatchIndex then
                ketikOpsi(State.CurrentMatches[State.MatchIndex])
            end
        end
    end
end)

-- Anti AFK
LP.Idled:Connect(function()
    if Config.AntiAFK then
        VU:Button2Down(Vector2.new(0,0), workspace.CurrentCamera.CFrame)
        task.wait(1)
        VU:Button2Up(Vector2.new(0,0), workspace.CurrentCamera.CFrame)
        log("Anti-AFK dipicu")
    end
end)

-- AFK Farm
task.spawn(function()
    while true do
        task.wait(3)
        if Config.AFKFarm and Config.SavedCFrame and LP.Character and LP.Character:FindFirstChild("HumanoidRootPart") then
            pcall(function()
                LP.Character.HumanoidRootPart.CFrame = Config.SavedCFrame
            end)
        end
    end
end)

log("Script siap! Database berisi " .. #kataKBBI .. " kata contoh.")
Rayfield:Notify({
    Title = "Script siap!",
    Content = "Database contoh: BUKU, KATA, MAKAN, ..."
})
